/*
*  Copyright (c) 2019. All right reserved
* Created on 2022-08-24 ( Date ISO 2022-08-24 - Time 12:58:26 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.maan.eway.master.dropdown.service;

import com.maan.eway.master.dropdown.req.BankMasterGetAllReq;
import com.maan.eway.master.dropdown.req.BankMasterGetReq;
import com.maan.eway.master.dropdown.req.BankMasterSaveReq;
import com.maan.eway.master.dropdown.req.CustomerSaveReq;
import com.maan.eway.master.dropdown.res.BankMasterRes;
import com.maan.eway.error.Error;
import com.maan.eway.res.DropDownRes;
import com.maan.eway.res.SuccessRes;

import java.util.List;
/**
* <h2>BankMasterServiceimpl</h2>
*/
public interface BankMasterService  {

/*BankMaster create(BankMaster d);
BankMaster update(BankMaster d);
//BankMaster getOne(long id) ;
 List<BankMaster> getAll();
long getTotal();
//boolean delete(long id);*/

List<DropDownRes> getBankMasterDropdown();
/*SuccessRes insertBank(BankMasterSaveReq req);

List<Error> validateBankDetails(BankMasterSaveReq req);

List<BankMasterRes> getallBankDetails(BankMasterGetAllReq req);

BankMasterRes getByBankCode(BankMasterGetReq req);



List<BankMasterRes> getActiveBankDetails(BankMasterGetAllReq req);



*/
}
