/*
*  Copyright (c) 2019. All right reserved
* Created on 2022-08-24 ( Date ISO 2022-08-24 - Time 12:58:26 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.maan.eway.master.dropdown.service;


import com.maan.eway.master.dropdown.req.CityChangeStatusReq;
import com.maan.eway.master.dropdown.req.CityMasterDropDownReq;
import com.maan.eway.master.dropdown.req.CityMasterGetAllReq;
import com.maan.eway.master.dropdown.req.CityMasterGetReq;
import com.maan.eway.master.dropdown.req.CityMasterSaveReq;
import com.maan.eway.master.dropdown.res.CityMasterRes;
import com.maan.eway.error.Error;
import com.maan.eway.res.DropDownRes;
import com.maan.eway.res.SuccessRes;

import java.util.List;
/**
* <h2>BankMasterServiceimpl</h2>
*/
public interface CityMasterService  {

	List<Error> validateDropdownGet(CityMasterDropDownReq req);

	List<DropDownRes> getCityMasterDropdown(CityMasterDropDownReq req);

/*
	List<Error> validateCityDetails(CityMasterSaveReq req);

	List<CityMasterRes> getActiveCityDetails(CityMasterGetAllReq req);

	SuccessRes insertCity(CityMasterSaveReq req);

	List<CityMasterRes> getallCityDetails(CityMasterGetAllReq req);

	CityMasterRes getByCityId(CityMasterGetReq req);
	
	SuccessRes changeStatusOfCity(CityChangeStatusReq req);

	*/
	

}
