/*
*  Copyright (c) 2019. All right reserved
* Created on 2022-08-24 ( Date ISO 2022-08-24 - Time 12:58:26 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.maan.eway.master.dropdown.service;

import com.maan.eway.master.dropdown.req.CountryChangeStatusReq;
import com.maan.eway.master.dropdown.req.CountryMasterGetAllReq;
import com.maan.eway.master.dropdown.req.CountryMasterGetReq;
import com.maan.eway.master.dropdown.req.CountryMasterSaveReq;
import com.maan.eway.master.dropdown.res.CountryMasterRes;
import com.maan.eway.error.Error;
import com.maan.eway.res.DropDownRes;
import com.maan.eway.res.SuccessRes;

import java.util.List;
/**
* <h2>BankMasterServiceimpl</h2>
*/
public interface CountryMasterService  {
	
	List<DropDownRes> getCountryMasterDropdown();
	/*
	List<Error> validateCountryDetails(CountryMasterSaveReq req);

	SuccessRes insertCountry(CountryMasterSaveReq req);

	List<CountryMasterRes> getallCountryDetails(CountryMasterGetAllReq req);

	List<CountryMasterRes> getActiveCountryDetails(CountryMasterGetAllReq req);

	CountryMasterRes getByCountryId(CountryMasterGetReq req);

	SuccessRes changeStatusOfCountry(CountryChangeStatusReq req);
*/
}
