/*
*  Copyright (c) 2019. All right reserved
* Created on 2022-08-24 ( Date ISO 2022-08-24 - Time 12:58:26 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.maan.eway.master.dropdown.service;

import com.maan.eway.master.dropdown.req.BankMasterGetAllReq;
import com.maan.eway.master.dropdown.req.BankMasterGetReq;
import com.maan.eway.master.dropdown.req.BankMasterSaveReq;
import com.maan.eway.master.dropdown.req.RegionChangeStatusReq;
import com.maan.eway.master.dropdown.req.RegionMasterDropDownReq;
import com.maan.eway.master.dropdown.req.RegionMasterGetAllReq;
import com.maan.eway.master.dropdown.req.RegionMasterGetReq;
import com.maan.eway.master.dropdown.req.RegionMasterSaveReq;
import com.maan.eway.master.dropdown.res.BankMasterRes;
import com.maan.eway.master.dropdown.res.RegionMasterRes;
import com.maan.eway.error.Error;
import com.maan.eway.res.DropDownRes;
import com.maan.eway.res.SuccessRes;

import java.util.List;
/**
* <h2>BankMasterServiceimpl</h2>
*/
public interface RegionMasterService  {
	List<DropDownRes> getRegionMasterDropdown(RegionMasterDropDownReq req);
/*
	List<Error> validateRegionDetails(RegionMasterSaveReq req);

	SuccessRes insertRegion(RegionMasterSaveReq req);

	List<RegionMasterRes> getallRegionDetails(RegionMasterGetAllReq req);

	List<RegionMasterRes> getActiveRegionDetails(RegionMasterGetAllReq req);

	RegionMasterRes getByRegionCode(RegionMasterGetReq req);

	SuccessRes changeStatusOfRegion(RegionChangeStatusReq req);

*/

}
