/*
*  Copyright (c) 2019. All right reserved
* Created on 2022-08-24 ( Date ISO 2022-08-24 - Time 12:58:26 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.maan.eway.master.dropdown.service;

import com.maan.eway.master.dropdown.req.StateMasterChangeStatusReq;
import com.maan.eway.master.dropdown.req.StateMasterDropDownReq;
import com.maan.eway.master.dropdown.req.StateMasterGetAllReq;
import com.maan.eway.master.dropdown.req.StateMasterGetReq;
import com.maan.eway.master.dropdown.req.StateMasterSaveReq;
import com.maan.eway.master.dropdown.res.StateMasterRes;
import com.maan.eway.error.Error;
import com.maan.eway.res.DropDownRes;
import com.maan.eway.res.SuccessRes;

import java.util.List;
/**
* <h2>BankMasterServiceimpl</h2>
*/
public interface StateMasterService  {
	List<DropDownRes> getStateMasterDropdown(StateMasterDropDownReq req);
/*

	List<Error> validateStateDetails(StateMasterSaveReq req);

	SuccessRes insertState(StateMasterSaveReq req);

	List<StateMasterRes> getallStateDetails(StateMasterGetAllReq req);

	List<StateMasterRes> getActiveStateDetails(StateMasterGetAllReq req);

	StateMasterRes getByStateId(StateMasterGetReq req);

	SuccessRes changeStatusOfStateMaster(StateMasterChangeStatusReq req);
*/

}
