#INS_PMT_CLAIM_UG=SELECT pp.POLH_SYS_ID POLH_SYS_ID, pp.POLH_NO POLH_NO, pp.POLH_PROD_CODE POLH_PROD_CODE, pp.POLH_DIVN_CODE POLH_DIVN_CODE, pp.POLH_END_NO_IDX POLH_END_NO_IDX, pp.POLH_END_SR_NO POLH_END_SR_NO, pp.POLH_COMP_CODE POLH_COMP_CODE, pp.POLH_DEPT_CODE POLH_DEPT_CODE, pp.POLH_CLASS_CODE POLH_CLASS_CODE, pp.POLH_CUST_CODE POLH_CUST_CODE, pp.POLH_ASSR_CODE POLH_ASSR_CODE, pp.POLH_ASSR_NAME POLH_ASSR_NAME, pp.POLH_FAC_YN POLH_FAC_YN, cid.ACCIDENT_DATE ACCIDENT_DATE, cid.ENTRY_DATE ENTRY_DATE, sysdate CURRENT_DATE, cid.CREATED_BY CREATED_BY, cid.REMARKS REMARKS, cid.ASSIGNED_DATE APPROVED_DATE, cid.CLAIM_OFFICER_ID CLAIM_OFFICER_ID, cid.LATTITUDE LATTITUDE, cid.LONGTITUDE LONGTITUDE, cid.ASSURED_NAME ASSURED_NAME, cid.ASSURED_ADDRESS ASSURED_ADDRESS, cid.CONTACT_NO CONTACT_NO, cid.FAX_NO FAX_NO, cid.EMAIL EMAIL, cid.INSIDEAFRICA_YN INSIDEAFRICA_YN, sysdate CLM_YEAR FROM pgith_pol_risk_addl_info ppr, pgith_policy pp,claim_intimation_detail cid WHERE pp.polh_no =cid.policy_no AND nvl(ppr.praih_data_03,ppr.praih_data_01) =cid.chassissno AND cid.claim_ref_no=? and pp.polh_end_no_idx =( SELECT MAX(polh_end_no_idx) FROM pgith_policy pp1 WHERE pp1.polh_no = pp.polh_no) AND ppr.praih_pol_sys_id = pp.polh_sys_id AND ppr.praih_end_no_idx = pp.polh_end_no_idx
INS_MOTOR_DATA=SELECT COMPANY_ID , BRANCH_CODE , PRODUCT_ID , SECTION_ID ,REQUEST_REFERENCE_NO ,QUOTE_NO FROM home_position_master WHERE QUOTE_NO=?1
 
       
                                        
  
  
     
                        
  
 
  
      
         
 
 
 
 
 
 
 
 
 
  
 
 
  
 
 
 
 
 
 
 
 
 
  
 
 
 
 
 
 
 
 
 
 
 
    
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
 
   
            
        
              
            
                                                    
              
             
             
       
         
 
       
        
           
           
          
            
                
                




 
  







    










 



      
   

  
  
  
  
  
  
  
  
  
          
  
  
  
  
  
   
  
 
 
 
 





      
  



  
 



  


  

  
 



