/*
 * Java domain class for entity "`" 
 * Created on 2022-08-24 ( Date ISO 2022-08-24 - Time 12:58:27 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
* Created on 2022-08-24 ( 12:58:27 )
* Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
*/

package com.maan.eway.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.eway.bean.EmiTransactionDetails;
import com.maan.eway.bean.EmiTransactionDetailsId;

public interface EmiTransactionDetailsRepository extends JpaRepository<EmiTransactionDetails, EmiTransactionDetailsId>,
		JpaSpecificationExecutor<EmiTransactionDetails> {

	List<EmiTransactionDetails> findByQuoteNoAndCompanyIdAndProductId(String quoteNo, String companyId,
			String productId);

	List<EmiTransactionDetails> findTop1ByQuoteNoAndPaymentStatusOrderByDueDateAsc(String string, String string2 );

	EmiTransactionDetails findByQuoteNoAndInstalmentAndInstallmentPeriod(String quoteNo, String installmentMonth,
			String installmentPeriod);

	//List<EmiTransactionDetails> findTop2ByQuoteNoAndPaymentStatusOrderByDueDateAsc(String quoteNo, String string);

	List<EmiTransactionDetails> findTop1ByQuoteNoAndCompanyIdAndPaymentStatusOrderByDueDateAsc(String quoteNo,
			String companyId, String string);

	List<EmiTransactionDetails> findTop1ByQuoteNoAndPaymentStatusOrderByDueDateDesc(String quoteNo, String string);

	List<EmiTransactionDetails> findByQuoteNoAndCompanyIdAndProductIdOrderByInstalmentAsc(String quoteNo,
			String companyId, String string);

	List<EmiTransactionDetails> findByQuoteNoAndInstallmentPeriod(String quoteNo, String installmentPeriod);

	List<EmiTransactionDetails> findByQuoteNoAndSelectYn(String quoteNo, String string);

	List<EmiTransactionDetails> findByQuoteNoAndSelectYnOrderByInstalmentDesc(String quoteNo, String string);






	

}
