/*
 * Java domain class for entity "EserviceTravelDetails" 
 * Created on 2022-11-30 ( Date ISO 2022-11-30 - Time 17:06:34 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-11-30 ( 17:06:34 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import java.math.BigDecimal;
import java.util.List;

import com.maan.eway.bean.EserviceMotorDetails;
import com.maan.eway.bean.EserviceTravelDetails;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import com.maan.eway.bean.EserviceTravelDetailsId;
import com.maan.eway.bean.EserviceTravelGroupDetails;
/**
 * <h2>EserviceTravelDetailsRepository</h2>
 *
 * createdAt : 2022-11-30 - Time 17:06:34
 * <p>
 * Description: "EserviceTravelDetails" Repository
 */
 
 
 
public interface EserviceTravelDetailsRepository  extends JpaRepository<EserviceTravelDetails,EserviceTravelDetailsId > , JpaSpecificationExecutor<EserviceTravelDetails> {

	EserviceTravelDetails findByRequestReferenceNo(String requestReferenceNo);

	EserviceTravelDetails findByRequestReferenceNoAndRiskIdAndCompanyIdAndProductIdAndSectionId(
			String requestReferenceNo, Integer vehicleId,  String companyId, String productId,
			String sectionId);

	EserviceTravelDetails findByRequestReferenceNoAndCompanyIdAndProductIdAndSectionId(String requestReferenceNo,
			String companyId, String productId, String sectionId);
	EserviceTravelDetails findByRequestReferenceNoAndQuoteNoAndProductIdAndCompanyId(String requestReferenceNo,
			String quoteNo, String productId, String companyId);

	List<EserviceTravelDetails> findByRequestReferenceNoAndProductId(String requestReferenceNo, String productId);

	Integer countByOriginalPolicyNo(String policyNo);

	List<EserviceTravelDetails> findByOriginalPolicyNo(String policyNo);

	Integer countByOriginalPolicyNoAndRiskId(String policyNo, int i);

	List<EserviceTravelDetails> findByOriginalPolicyNoAndRiskId(String policyNo, int i);

	List<EserviceTravelDetails> findByPolicyNoAndStatus(String policyNo, String string);

	List<EserviceTravelDetails> findByQuoteNoOrderByRiskIdAsc(String prevQuoteNo);

	List<EserviceTravelDetails> findByPolicyNoAndRiskId(String prevPolicyNo, int i);

	List<EserviceTravelDetails> findByCustomerId(String customerId);

	EserviceTravelDetails findByRequestReferenceNoOrderBySectionNameAsc(String requestReferenceNo);

	EserviceTravelDetails findByQuoteNoAndSectionIdAndProductIdOrderByRiskIdAsc(String quoteNo, String sectionId,
			String productId);
/*
	EserviceTravelDetails findByQuoteNoAndSectionIdAndProductIdOrderByRiskIdAsc(String quoteNo, Integer sectionId,
			Integer productId);
*/
	List<EserviceTravelDetails> findByPolicyNo(String prevPolicyNo);

	EserviceTravelDetails findByQuoteNo(String quoteNo);

}
