/*
 * Java domain class for entity "FactorRateRequestDetails" 
 * Created on 2022-11-08 ( Date ISO 2022-11-08 - Time 16:28:23 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-11-08 ( 16:28:23 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import java.math.BigDecimal;
import java.util.List;

import javax.transaction.Transactional;

import com.maan.eway.bean.FactorRateRequestDetails;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import com.maan.eway.bean.FactorRateRequestDetailsId;
/**
 * <h2>FactorRateRequestDetailsRepository</h2>
 *
 * createdAt : 2022-11-08 - Time 16:28:23
 * <p>
 * Description: "FactorRateRequestDetails" Repository
 */
 
 
 
public interface FactorRateRequestDetailsRepository  extends JpaRepository<FactorRateRequestDetails,FactorRateRequestDetailsId > , JpaSpecificationExecutor<FactorRateRequestDetails> {

	void deleteByRequestReferenceNoAndVehicleId(String requestReferenceNo, Integer vehicleId);

	Long countByRequestReferenceNoAndVehicleId(String requestReferenceNo, Integer vehicleId);

	List<FactorRateRequestDetails> findByRequestReferenceNoAndVehicleIdOrderByCoverIdAsc(String requestReferenceNo, Integer vehicleId);

	List<FactorRateRequestDetails> findByRequestReferenceNoAndDiscLoadIdOrderByVehicleIdAsc(String requestReferenceNo,
			int i);

	List<FactorRateRequestDetails> findByRequestReferenceNoAndVehicleIdOrderByVehicleIdAsc(String requestReferenceNo,
			Integer vehicleId);

	List<FactorRateRequestDetails> findByRequestReferenceNoAndDiscLoadIdAndVehicleIdOrderByVehicleIdAsc(
			String requestReferenceNo, int i, Integer vehicleId);

	List<FactorRateRequestDetails> findByRequestReferenceNoOrderByVehicleIdAsc(String requestReferenceNo);

	
	List<FactorRateRequestDetails> findByRequestReferenceNoAndDiscLoadIdAndTaxIdAndUserOptOrderByVehicleIdAsc(
			String requestReferenceNo, int i, int j, String string);

	List<FactorRateRequestDetails> findByRequestReferenceNoAndVehicleIdAndCompanyIdAndProductIdAndSectionIdOrderByCoverIdAsc(
			String requestReferenceNo, Integer valueOf, String insuranceId, Integer valueOf2, Integer valueOf3);
	@Transactional
	void deleteByRequestReferenceNoAndVehicleIdAndCompanyIdAndProductIdAndSectionId(String requestReferenceNo,
			Integer valueOf, String insuranceId, Integer valueOf2, Integer valueOf3);

	List<FactorRateRequestDetails> findByRequestReferenceNoAndProductIdAndSectionIdAndDiscLoadIdAndVehicleIdOrderByVehicleIdAsc(
			String requestReferenceNo, Integer valueOf, Integer valueOf2, int i, Integer groupId);

	List<FactorRateRequestDetails> findByRequestReferenceNoAndVehicleIdAndSectionIdOrderByVehicleIdAsc(
			String requestReferenceNo, Integer vehicleId, Integer valueOf);

	List<FactorRateRequestDetails> findByRequestReferenceNoAndProductIdAndSectionIdAndVehicleIdOrderByVehicleIdAsc(
			String requestReferenceNo, Integer valueOf, Integer valueOf2, Integer vehicleId);


	Long countByRequestReferenceNoAndVehicleIdAndCompanyIdAndProductIdAndSectionId(String requestReferenceNo,
			Integer valueOf, String insuranceId, Integer valueOf2, Integer valueOf3);

	List<FactorRateRequestDetails> findByRequestReferenceNoAndDiscLoadIdAndVehicleIdAndProductIdAndSectionIdOrderByVehicleIdAsc(
			String requestReferenceNo, int i, Integer vehicleId, Integer valueOf, Integer valueOf2);

	List<FactorRateRequestDetails> findByRequestReferenceNoAndDiscLoadIdAndUserOptOrderByVehicleIdAsc(
			String requestReferenceNo, int i, String string);

	List<FactorRateRequestDetails> findByRequestReferenceNoAndDiscLoadIdAndTaxIdAndVehicleIdAndProductIdAndSectionIdOrderByVehicleIdAsc(
			String requestReferenceNo, int i, int j, Integer vehicleId, Integer valueOf, Integer valueOf2);

	List<FactorRateRequestDetails> findByRequestReferenceNoAndDiscLoadIdAndTaxIdAndUserOptAndVehicleIdAndProductIdAndSectionIdOrderByVehicleIdAsc(
			String requestReferenceNo, int i, int j, String string, Integer vehicleId, Integer valueOf,
			Integer valueOf2);

	List<FactorRateRequestDetails> findByRequestReferenceNoAndDiscLoadIdAndTaxIdAndVehicleIdAndProductIdAndSectionIdNotOrderByVehicleIdAsc(
			String requestReferenceNo, int i, int j, Integer groupId, Integer valueOf, int k);

	List<FactorRateRequestDetails> findByRequestReferenceNoAndVehicleIdAndProductIdAndSectionIdOrderByCoverIdAsc(
			String requestReferenceNo, Integer vehicleId, Integer productId, Integer sectionId);


}
