/*
 * Java domain class for entity "InsuranceCompanyMaster" 
 * Created on 2022-08-24 ( Date ISO 2022-08-24 - Time 12:58:27 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-08-24 ( 12:58:27 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import java.util.Date;
import java.util.List;
import java.util.Map;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
import org.springframework.data.jpa.repository.Query;

import com.maan.eway.bean.InsuranceCompanyMaster;
import com.maan.eway.bean.InsuranceCompanyMasterId;
/**
 * <h2>InsuranceCompanyMasterRepository</h2>
 *
 * createdAt : 2022-08-24 - Time 12:58:27
 * <p>
 * Description: "InsuranceCompanyMaster" Repository
 */
 
 
 
public interface InsuranceCompanyMasterRepository  extends JpaRepository<InsuranceCompanyMaster,InsuranceCompanyMasterId > , JpaSpecificationExecutor<InsuranceCompanyMaster> {

	InsuranceCompanyMaster findByCompanyId(String insuranceId);
	
	//List<InsuranceCompanyMaster> findTopByCompanyIdOrderByAmendIdDescAndPatternStatus(Object string,String pp);

	List<InsuranceCompanyMaster> findTopByCompanyIdOrderByAmendIdDesc(String companyId);

	List<InsuranceCompanyMaster> findByCompanyIdOrderByAmendIdDesc(String companyId);

	List<InsuranceCompanyMaster> findByCompanyIdAndStatusOrderByEffectiveDateEndDesc(String companyId, String string);

	List<InsuranceCompanyMaster> findByCompanyIdAndStatusAndEffectiveDateStartAfterAndEffectiveDateEndBefore(String companyId,
			String string, Date date, Date date2);

	List<InsuranceCompanyMaster> findByCompanyIdAndStatusAndEffectiveDateStartBeforeAndEffectiveDateEndAfter(
			String companyId, String string, Date date, Date date2);

	@Query(value = "SELECT * FROM eway_insurance_company_master ew WHERE company_id = ?1 AND amend_id = (SELECT MAX(amend_id) FROM eway_insurance_company_master WHERE company_id = ew.company_id)", nativeQuery=true)
	List<Map<String,Object>> getCompanyDetailsById(String companyId);

	

}
