/*
 * Java domain class for entity "OtpDataDetail" 
 * Created on 2023-07-06 ( Date ISO 2023-07-06 - Time 17:58:04 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2023-07-06 ( 17:58:04 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import java.util.Date;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.eway.bean.OtpDataDetail;
import com.maan.eway.bean.OtpDataDetailId;
/**
 * <h2>OtpDataDetailRepository</h2>
 *
 * createdAt : 2023-07-06 - Time 17:58:04
 * <p>
 * Description: "OtpDataDetail" Repository
 */
 
 
 
public interface OtpDataDetailRepository  extends JpaRepository<OtpDataDetail,OtpDataDetailId > , JpaSpecificationExecutor<OtpDataDetail> {

	OtpDataDetail findByCompanyIdAndProductIdAndOtpId(String companyId, String productId, Long otpToken);

	OtpDataDetail findByCompanyIdAndProductIdAndOtpIdAndExpiryDateIsAfter(String companyId, String productId,
			Long otpToken,Date date);

	Integer countByCompanyIdAndProductIdAndOtpIdAndOtpAndExpiryDateIsAfter(String companyId, String productId,
			Long otpToken, String userOtp, Date date);

	Integer countByCompanyIdAndProductIdAndOtpIdAndOtp(String companyId, String productId, Long otpToken,
			String userOtp);

}
