/*
 * Java domain class for entity "PolicyCoverDataEndt" 
 * Created on 2023-08-22 ( Date ISO 2023-08-22 - Time 11:27:54 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2023-08-22 ( 11:27:54 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.eway.bean.PolicyCoverDataEndt;
import com.maan.eway.bean.PolicyCoverDataEndtId;
/**
 * <h2>PolicyCoverDataEndtRepository</h2>
 *
 * createdAt : 2023-08-22 - Time 11:27:54
 * <p>
 * Description: "PolicyCoverDataEndt" Repository
 */
 
 
 
public interface PolicyCoverDataEndtRepository  extends JpaRepository<PolicyCoverDataEndt,PolicyCoverDataEndtId > , JpaSpecificationExecutor<PolicyCoverDataEndt> {

	List<PolicyCoverDataEndt> findByPolicyNo(String originalPolicyNo);

	List<PolicyCoverDataEndt> findByPolicyNoAndVehicleIdAndCompanyIdAndProductIdAndSectionIdOrderByCoverIdAsc(
			String originalPolicyNo, int parseInt, String insuranceId, int parseInt2, int parseInt3);

}
