/*
 * Java domain class for entity "SeqCreditno" 
 * Created on 2023-01-12 ( Date ISO 2023-01-12 - Time 16:01:57 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2023-01-12 ( 16:01:57 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import java.math.BigDecimal;

import com.maan.eway.bean.SeqCreditno;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;
/**
 * <h2>SeqCreditnoRepository</h2>
 *
 * createdAt : 2023-01-12 - Time 16:01:57
 * <p>
 * Description: "SeqCreditno" Repository
 */
 
 
 
public interface SeqCreditnoRepository  extends JpaRepository<SeqCreditno,Long > , JpaSpecificationExecutor<SeqCreditno> {

}
