/*
 * Java domain class for entity "BankMaster" 
 * Created on 2022-08-24 ( Date ISO 2022-08-24 - Time 12:58:26 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2022-08-24 ( 12:58:26 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.eway.bean.TermsAndCondition;
import com.maan.eway.bean.TermsAndConditionId;
/**
 * <h2>BankMasterRepository</h2>
 *
 * createdAt : 2022-08-24 - Time 12:58:26
 * <p>
 * Description: "BankMaster" Repository
 */
 
 
 
public interface TermsAndConditionRepository  extends JpaRepository<TermsAndCondition,TermsAndConditionId > , JpaSpecificationExecutor<TermsAndCondition> {




	List<TermsAndCondition> findByCompanyIdAndBranchCodeAndProductIdAndSectionIdAndRiskIdAndQuoteNoAndId(
			String companyId, String branchCode, String productId, String sectionId, String riskId, String quoteNo,
			Integer valueOf);


	TermsAndCondition findByCompanyIdAndBranchCodeAndProductIdAndSectionIdAndRiskIdAndQuoteNoAndIdAndSubId(
			String companyId, String branchCode, String productId, String sectionId, String riskId, String quoteNo,
			Integer valueOf, Integer valueOf2);


	List<TermsAndCondition> findByQuoteNoAndRiskIdAndProductIdAndSectionId(String quoteNo, String riskId,
			String productId, String sectionId);




}
