/*
 * Java domain class for entity "BankMaster" 
 * Created on 2021-10-12 ( Date ISO 2021-10-12 - Time 16:17:06 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2021-10-12 ( 16:17:06 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.repository;

import java.util.List;



import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.eway.bean.YiCoverDetail;
import com.maan.eway.bean.YiCoverDetailId;
/**
 * <h2>BankMasterRepository</h2>
 *
 * createdAt : 2021-10-12 - Time 16:17:06
 * <p>
 * Description: "BankMaster" Repository
 */
 
 
 
public interface YiCoverDetailRepository  extends JpaRepository<YiCoverDetail,YiCoverDetailId > , JpaSpecificationExecutor<YiCoverDetail> {

	List<YiCoverDetail> findByQuotationPolicyNo(String policyNo);

	List<YiCoverDetail> findByRequestreferenceno(String reqRefNo);



}
