/*
 * Java domain class for entity "PremiaRiskDetail" 
 * Created on 2021-08-02 ( Date ISO 2021-08-02 - Time 16:59:39 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.maan.eway.integration.req;

import java.io.Serializable;

import lombok.*;
import java.math.BigDecimal;
import java.util.Date;

import java.math.BigDecimal;
import java.util.Date;
import jakarta.persistence.*;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;

/**
 * Domain class for entity "PremiaRiskDetail"
 *
 * @author Telosys Tools Generator
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class MotDriverDetailReq implements Serializable {

	private static final long serialVersionUID = 1L;

	@JsonProperty("Requestreferenceno")
	private String requestreferenceno;

	@JsonProperty("SerialNo")
	private Double serialNo;

	@JsonProperty("ServiceId")
	private String serviceId;

	@JsonProperty("ServiceAction")
	private String serviceAction;

	@JsonProperty("QuotationPolicyNo")
	private String quotationPolicyNo;

	@JsonProperty("SecCode")
	private String secCode;

	@JsonProperty("L1s2Id")
	private Long l1s2Id;

	@JsonProperty("IterationNo")
	private String iterationNo;

	@JsonProperty("Name")
	private String name;

	@JsonProperty("DateOfBirth")
	private Date dateOfBirth;

	@JsonProperty("Sex")
	private String sex;

	@JsonProperty("IdResidentNo")
	private String idResidentNo;

	@JsonProperty("TypeOfClass")
	private String typeOfClass;

	@JsonProperty("RequestTime")
	private Date requestTime;

	@JsonProperty("ResponseTime")
	private Date responseTime;

	@JsonProperty("Status")
	private String status;

	@JsonProperty("PWsResponseType")
	private String pWsResponseType;

	@JsonProperty("PWsError")
	private String pWsError;

	@JsonProperty("EntryDate")
	private Date entryDate;

	@JsonProperty("QuoteNo")
	private String quoteNo;

	@JsonProperty("RenewalPolicyNo")
	private String renewalPolicyNo;

	@JsonProperty("ProductCode")
	private String productCode;

	@JsonProperty("LicenseIssuedOn")
	private Date licenseIssuedOn;
	
	@JsonProperty("RiskId")
	private Integer    riskId ;
	
	@JsonProperty("DrvrEndNoIdx")
	private String drvrEndNoIdx;

}