/*
 * Java domain class for entity "PremiaRiskDetail" 
 * Created on 2021-08-02 ( Date ISO 2021-08-02 - Time 16:59:39 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.maan.eway.integration.req;
import java.io.Serializable;

import lombok.*;
import java.math.BigDecimal;
import java.util.Date;


import java.math.BigDecimal;
import java.util.Date;
import jakarta.persistence.*;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;



/**
 * Domain class for entity "PremiaRiskDetail"
 *
 * @author Telosys Tools Generator
 *
 */
 
 
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class YiChargeDetailReq implements Serializable {

    private static final long serialVersionUID = 1L;
    
	@JsonProperty("ChargeCode")
	private String chargeCode;

	@JsonProperty("Requestreferenceno")
	private String requestreferenceno;

	@JsonProperty("ServiceId")
	private String serviceId;

	@JsonProperty("QuotationPolicyNo")
	private String quotationPolicyNo;

	@JsonProperty("ServiceAction")
	private String serviceAction;

	@JsonProperty("ChgId")
	private BigDecimal chgId;

	@JsonProperty("IndexNo")
	private String indexNo;

	@JsonProperty("ChargeRate")
	private Double chargeRate;

	@JsonProperty("RateModifiedYn")
	private String rateModifiedYn;

	@JsonProperty("ChargeAmount")
	private Double chargeAmount;

	@JsonProperty("ChargeModifiedYn")
	private String chargeModifiedYn;

	@JsonProperty("ProdCode")
	private String prodCode;

	@JsonProperty("PWsResponseType")
	private String pWsResponseType;

	@JsonProperty("PWsError")
	private String pWsError;

	@JsonProperty("RequestTime")
	private Date requestTime;

	@JsonProperty("ResponseTime")
	private Date responseTime;

	@JsonProperty("Status")
	private String status;
	
	@JsonProperty("VatSrNo")
    private String     vatSrNo ;
    
	@JsonProperty("VatApplyOn")
    private String     vatApplyOn ;
	
	@JsonProperty("CrgEndNoIdx")
    private String     crgEndNoIdx ;
}