/*
 * Java domain class for entity "PremiaRiskDetail" 
 * Created on 2021-08-02 ( Date ISO 2021-08-02 - Time 16:59:39 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.maan.eway.integration.req;
import java.io.Serializable;

import lombok.*;
import java.math.BigDecimal;
import java.util.Date;


import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;



/**
 * Domain class for entity "PremiaRiskDetail"
 *
 * @author Telosys Tools Generator
 *
 */
 
 
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class YiChargeDetailReq implements Serializable {

    private static final long serialVersionUID = 1L;

    //----------------------------------------------------------------------
    // ENTITY PRIMARY KEY 
    //----------------------------------------------------------------------

	@JsonProperty("ClmapSysId")
	private Long clmapSysId;

	@JsonProperty("ClmapPolSysId")
	private Long clmapPolSysId;

	@JsonProperty("ClmapSectionCode")
	private String clmapSectionCode;

	@JsonProperty("ClmapPolNo")
	private String clmapPolNo;

	@JsonProperty("ClmapCompCode")
	private String clmapCompCode;

	@JsonProperty("ClmapDivnCode")
	private String clmapDivnCode;

	@JsonProperty("ClmapProdCode")
	private String clmapProdCode;

	@JsonProperty("ClmapDeptCode")
	private String clmapDeptCode;

	@JsonProperty("ClmapReinstDoneYn")
	private String clmapReinstDoneYn;

	@JsonFormat(pattern = "dd/MM/yyyy")
	@JsonProperty("ClmapCrDt")
	private Date clmapCrDt;

	@JsonProperty("ClmapCrUid")
	private String clmapCrUid;

	@JsonFormat(pattern = "dd/MM/yyyy")
	@JsonProperty("ClmapUpdDt")
	private Date clmapUpdDt;

	@JsonProperty("ClmapUpdUid")
	private String clmapUpdUid;

	@JsonProperty("ClmapTotLossYn")
	private String clmapTotLossYn;

	@JsonProperty("ClmapPsecSysId")
	private String clmapPsecSysId;

	@JsonProperty("ClmapEndNoIdx")
	private Integer clmapEndNoIdx;

	@JsonProperty("ClmapEndSrNo")
	private Integer clmapEndSrNo;

	@JsonProperty("ClmapCoverCode")
	private String clmapCoverCode;

	@JsonProperty("ClmapPraiLvl1SysId")
	private Long clmapPraiLvl1SysId;

	@JsonProperty("ClmapPraiLvl1SrNo")
	private Long clmapPraiLvl1SrNo;

	@JsonProperty("ClmapPraiLvl1Desc")
	private String clmapPraiLvl1Desc;

	@JsonProperty("ClmapPraiLvl2SysId")
	private Long clmapPraiLvl2SysId;

	@JsonProperty("ClmapPraiLvl2SrNo")
	private Long clmapPraiLvl2SrNo;

	@JsonProperty("ClmapPraiLvl2Desc")
	private String clmapPraiLvl2Desc;

	@JsonProperty("ClmapPraiLvl3SysId")
	private Long clmapPraiLvl3SysId;

	@JsonProperty("ClmapPraiLvl3SrNo")
	private Long clmapPraiLvl3SrNo;

	@JsonProperty("ClmapPraiLvl3Desc")
	private String clmapPraiLvl3Desc;

	@JsonProperty("ClmapRemarks")
	private String clmapRemarks;

	@JsonProperty("ClmapReinstReqdYn")
	private String clmapReinstReqdYn;

	@JsonProperty("ClmapLossCode")
	private String clmapLossCode;

	@JsonProperty("ClmapInviteRenYn")
	private String clmapInviteRenYn;

	@JsonProperty("ClmapRetainNcdYn")
	private String clmapRetainNcdYn;

	@JsonProperty("ClmapSmiCode")
	private String clmapSmiCode;

	@JsonProperty("ClmapSmiSysId")
	private Long clmapSmiSysId;

	@JsonProperty("lmapStolenYn")
	private String clmapStolenYn;

	@JsonProperty("ClmapClmSysId")
	private Long clmapClmSysId;

	@JsonProperty("PraihLvl1SysId")
	private String praihLvl1SysId;

	@JsonProperty("PraihLvl2SysId")
	private String praihLvl2SysId;

}