/*
 * Java domain class for entity "PremiaRiskDetail" 
 * Created on 2021-08-02 ( Date ISO 2021-08-02 - Time 16:59:39 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.maan.eway.integration.req;
import java.io.Serializable;

import lombok.*;
import java.math.BigDecimal;
import java.util.Date;


import com.fasterxml.jackson.annotation.JsonProperty;



/**
 * Domain class for entity "PremiaRiskDetail"
 *
 * @author Telosys Tools Generator
 *
 */
 
 
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class YiDeductableDetailReq implements Serializable {

    private static final long serialVersionUID = 1L;
    
    @JsonProperty("ServiceId")
    private String serviceId;

    @JsonProperty("QuotationPolicyNo")
    private String quotationPolicyNo;

    @JsonProperty("ServiceAction")
    private String serviceAction;

    @JsonProperty("ProdCode")
    private String prodCode;

    @JsonProperty("SecCode")
    private String secCode;

    @JsonProperty("RiskId")
    private String riskId;

    @JsonProperty("IdxNo")
    private Integer idxNo;

    @JsonProperty("DedSrNo")
    private Integer dedSrNo;

    @JsonProperty("DedCode")
    private String dedCode;

    @JsonProperty("DedDesc")
    private String dedDesc;

    @JsonProperty("DedType")
    private String dedType;

    @JsonProperty("DedPerc")
    private BigDecimal dedPerc;

    @JsonProperty("DedAmtFc")
    private BigDecimal dedAmtFc;

    @JsonProperty("DedAmtLc")
    private BigDecimal dedAmtLc;
    
    @JsonProperty("RequestReferenceNo")
    private String requestReferenceNo;

    @JsonProperty("WsResponseType")
    private String wsResponseType;

    @JsonProperty("WsError")
    private String wsError;

    @JsonProperty("RequestTime")
    private Date       requestTime ;

    @JsonProperty("ResponseTime")
    private Date       responseTime ;

    @JsonProperty("Status")
    private String status;
}