/*
 * Java domain class for entity "EserviceBuildingsDetails" 
 * Created on 2022-09-06 ( Date ISO 2022-09-06 - Time 11:31:29 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.maan.eway.res;

import java.io.Serializable;
import java.math.BigDecimal;

import lombok.*;
import java.util.Date;
import java.util.List;
import java.util.Date;
import jakarta.persistence.*;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;



/**
 * Domain class for entity "EserviceBuildingsDetails"
 *
 * @author Telosys Tools Generator
 *
 */
 
 
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class EserviceBuildingsDetailsRes implements Serializable {

    private static final long serialVersionUID = 1L;

    @JsonProperty("RiskId")
	private  String riskId;	
    
    @JsonProperty("DocumentsTitle")
    private String    documentsTitle;
    
	@JsonProperty("InbuildConstructType")
    private String     inbuildConstructType ;
	@JsonProperty("BuildingFloors")
    private String buildingFloors ;
	@JsonProperty("OutbuildConstructType")
    private String     outbuildConstructType ;
	@JsonProperty("BuildingUsageYn")
    private String     buildingUsageYn ;
	@JsonProperty("BuildingPurpose")
    private String     buildingPurpose;
	@JsonProperty("BuildingUsageDesc")
    private String     buildingUsageDesc ;
	@JsonProperty("BuildingPurposeId")
    private String     buildingPurposeId;
	@JsonProperty("BuildingUsageId")
    private String     buildingUsageId;

	@JsonProperty("PaDeathSuminsured")
    private String     paDeathSuminsured ;
	

	@JsonProperty("PaPermanentdisablementSuminsured")
    private String     paPermanentdisablementSuminsured ;
	
	@JsonProperty("PaTotaldisabilitySumInsured")
    private String     paTotaldisabilitySumInsured ;
	
	@JsonProperty("PaMedicalSuminsured")
    private String     paMedicalSuminsured ;
	
	@JsonProperty("BuildingType")
	private String     buildingType;

	@JsonProperty("BuildingOwnerYn")
	private String     buildingOwnerYn;
	@JsonProperty("PersonalIntermediarySuminsured")
    private String     personalIntermediarySuminsured ;
	
	
	@JsonProperty("BuildingOccupationType")
    private String     buildingOccupationType ;
	@JsonProperty("WithoutInhabitantDays")
    private String    withoutInhabitantDays ;

	@JsonProperty("BuildingCondition")
    private String     buildingCondition ;
	@JsonProperty("BuildingBuildYear")
    private String    buildingBuildYear ;
	
	@JsonProperty("BuidingAreaSqm")
    private String     buidingAreaSqm ;
	@JsonProperty("BuildingSuminsured")
    private String     buildingSuminsured ;
	@JsonProperty("AllriskSumInsured")
    private String     allriskSuminsured ;
	@JsonProperty("ContentSuminsured")
    private String     contentSuminsured ;
	
	@JsonProperty("DomesticPackageYn")
    private String    domesticPackageYn;

	@JsonProperty("EndorsementYn")
    private String     endorsementYn;
	
	@JsonProperty("SectionId")
	private  String sectionId;	

	@JsonProperty("Suminsured")
    private String     suminsured ;
	
	@JsonProperty("OccupationType")
    private String    occupationType;

	@JsonProperty("OccupationTypeDesc")
    private String    occupationTypeDesc;

	@JsonProperty("CategoryId")
    private String    categoryId;
	

	@JsonProperty("SectionDetails")
    private List<SectionDetails>    sectionDetails;


	@JsonProperty("PremiumLc")
    private Double premiumLc;	

	@JsonProperty("PremiumFc")
    private Double premiumFc;	

	@JsonProperty("OverAllPremiumFc")
    private Double overAllPremiumFc;	

	@JsonProperty("OverAllPremiumLc")
    private Double overAllPremiumLc;	

	@JsonProperty("CommissionAmount")
    private String commissionAmount;	

	@JsonProperty("CommissionPercentage")
    private String commissionPercentage;
	
	@JsonProperty("WallType")
    private String    wallType;
	
	@JsonProperty("WallTypeDesc")
    private String    wallTypeDesc;
	
	@JsonProperty("RoofType")
    private String    roofType;
	
	@JsonProperty("RoofTypeDesc")
    private String    roofTypeDesc;

	// Burglary Changes

    @JsonProperty("NatureOfTradeId")
    private String natureOfTradeId;
    
     @JsonProperty("NatureOfTradeDesc")
     private String     natureOfTradeDesc ;
    
     @JsonProperty("InsuranceForId")
     private Object insuranceForId ;
    
     @JsonProperty("InsuranceForDesc")
     private String     insuranceForDesc ;
    
     @JsonProperty("InternalWallType")
     private String internalWallType;
    
     @JsonProperty("InternalWallDesc")
     private String     internalWallDesc ;
    
     @JsonProperty("CeilingType")
     private String ceilingType;
    
     @JsonProperty("CeilingTypeDesc")
     private String     ceilingTypeDesc ;
    
     @JsonProperty("StockInTradeSi")
     private String stockInTradeSi ;
    
     @JsonProperty("GoodsSi")
     private String goodsSi;
    
     @JsonProperty("FurnitureSi")
     private String furnitureSi;
    
     @JsonProperty("ApplianceSi")
     private String applianceSi;
    
     @JsonProperty("CashValueablesSi")
     private String cashValueablesSi;
    
     @JsonProperty("Address")
     private String address;
    
     @JsonProperty("RegionCode")
     private String regionCode;
    
     @JsonProperty("RegionDesc")
     private String     regionDesc ;
    
     @JsonProperty("DistrictCode")
     private String districtCode ;
    
     @JsonProperty("DistrictDesc")
     private String     districtDesc ;
    
     @JsonProperty("OccupiedYear")
     private String occupiedYear;
    
     @JsonProperty("showWindow")
     private String showWindow;
    
     @JsonProperty("FrontDoors")
     private String frontDoors;
    
     @JsonProperty("BackDoors")
     private String backDoors;
    
     @JsonProperty("WindowsMaterialId")
     private String windowsMaterialId;
    
     @JsonProperty("WindowsMaterialDesc")
     private String     windowsMaterialDesc;
    
     @JsonProperty("DoorsMaterialId")
     private String doorsMaterialId; 
    
     @JsonProperty("DoorsMaterialDesc")
     private String     doorsMaterialDesc;
    
     @JsonProperty("NightLeftDoor")
     private String nightLeftDoor; 
    
     @JsonProperty("NightLeftDoorDesc")
     private String     nightLeftDoorDesc ;
    
     @JsonProperty("BuildingOccupied")
     private String buildingOccupied; 
    
     @JsonProperty("BuildingOccupiedDesc")
     private String     buildingOccupiedDesc;
    
     @JsonProperty("WatchmanGuardHours")
     private String watchmanGuardHours;
    
     @JsonProperty("AccessibleWindows")
     private String accessibleWindows;
     
     @JsonProperty("TrapDoors")
     private String trapDoors;

    @JsonProperty("MachineEquipSi")
     private BigDecimal machineEquipSi ;

    @JsonProperty("PlateGlassSi")
     private BigDecimal plateGlassSi ;
     
    @JsonProperty("FirstLossPercentId")
     private Integer firstLossPercentId;

    @JsonProperty("FirstLossPercent")
     private Integer firstLossPercent;

    @JsonProperty("AccDamageSi")
     private BigDecimal accDamageSi ;
       
    @JsonProperty("BurglarySi")
     private BigDecimal burglarySi ;
     
    @JsonProperty("PowerPlantSi")
     private BigDecimal powerPlantSi ;
     
    @JsonProperty("ElecMachinesSi")
     private BigDecimal elecMachinesSi ;
     
    @JsonProperty("EquipmentSi")
     private BigDecimal equipmentSi ;
     
    @JsonProperty("GeneralMachineSi")
     private BigDecimal generalMachineSi ;
     
    @JsonProperty("ManuUnitsSi")
     private BigDecimal manuUnitsSi ;
     
    @JsonProperty("BoilerPlantsSi")
     private BigDecimal boilerPlantsSi ;
     
    @JsonProperty("TiraCoverNoteNo")
     private String tiraCoverNoteNo;
     
    @JsonProperty("IndemityPeriod")
     private String indemityPeriod;
     
    @JsonProperty("IndemityPeriodDesc")
     private String indemityPeriodDesc;
     
     
    @JsonProperty("MakutiYn")
     private String makutiYn;
   
    @JsonProperty("PlateGlassType")
     private String plateGlassType;
     
    @JsonProperty("PlateGlassDesc")
     private String plateGlassDesc;
   
    @JsonProperty("StockLossPercent")
	private String stockLossPercent ;
  
    @JsonProperty("GoodsLossPercent")
  private String goodsLossPercent;
  
    @JsonProperty("FurnitureLossPercent")
  private String furnitureLossPercent;
  
    @JsonProperty("ApplianceLossPercent")
  private String applianceLossPercent;
  
    @JsonProperty("CashValueablesLossPercent")
  private String cashValueablesLossPercent;
  

	@JsonProperty("LocationId")
   	private  String locationId;	
    
    @JsonProperty("LocationName")
   	private  String locationName;
    
	@JsonProperty("MiningPlantSi")
	private String miningPlantSi;
	
	@JsonProperty("NonminingPlantSi")
	private String nonminingPlantSi;
	
	@JsonProperty("GensetsSi")
	private String gensetsSi;

	@JsonProperty("VatCommission")
	private String vatCommission;
 
	@JsonProperty("PolicyNo")
	private String policyNo;


	@JsonProperty("MoneySafeLimit")
    private String moneySafeLimit    ;
	
	@JsonProperty("MoneyOutofSafe")
    private String moneyOutofSafe    ;
	
	@JsonProperty("MoneyDirectorResidence")
    private String moneyDirectorResidence    ;
	
	@JsonProperty("MoneyCollector")
    private String moneyCollector    ;
	
	@JsonProperty("MoneyAnnualEstimate")
    private String moneyAnnualEstimate    ;
	
	@JsonProperty("MoneyMajorLoss")
    private String moneyMajorLoss;
	
	@JsonProperty("ElecEquipSuminsured")
	private BigDecimal ElecEquipSuminsured;
	
	@JsonProperty("MachinerySi")
    private String machinerySi;
	
	@JsonProperty("FireEquipSi")
    private String fireEquipSi;
	
	@JsonProperty("FirePlantSi")
    private String firePlantSi;
	
	
	@JsonProperty("BondSuminsured")
    private BigDecimal bondSuminsured;

	@JsonProperty("FinalyzeYn")
	private String finalizeYn;

}
