/*
 * Java domain class for entity "EserviceBuildingsDetails" 
 * Created on 2022-09-06 ( Date ISO 2022-09-06 - Time 11:31:29 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.maan.eway.res;

import java.io.Serializable;

import lombok.*;
import java.util.Date;
import java.util.List;
import java.util.Date;
import javax.persistence.*;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;



/**
 * Domain class for entity "EserviceBuildingsDetails"
 *
 * @author Telosys Tools Generator
 *
 */
 
 
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class EserviceBuildingsDetailsRes implements Serializable {

    private static final long serialVersionUID = 1L;

    @JsonProperty("RiskId")
	private  String riskId;	
    
    @JsonProperty("DocumentsTitle")
    private String    documentsTitle;
    
	@JsonProperty("InbuildConstructType")
    private String     inbuildConstructType ;
	@JsonProperty("BuildingFloors")
    private String buildingFloors ;
	@JsonProperty("OutbuildConstructType")
    private String     outbuildConstructType ;
	@JsonProperty("BuildingUsageYn")
    private String     buildingUsageYn ;
	@JsonProperty("BuildingPurpose")
    private String     buildingPurpose;
	@JsonProperty("BuildingUsageDesc")
    private String     buildingUsageDesc ;
	@JsonProperty("BuildingPurposeId")
    private String     buildingPurposeId;
	@JsonProperty("BuildingUsageId")
    private String     buildingUsageId;

	@JsonProperty("PaDeathSuminsured")
    private String     paDeathSuminsured ;
	

	@JsonProperty("PaPermanentdisablementSuminsured")
    private String     paPermanentdisablementSuminsured ;
	
	@JsonProperty("PaTotaldisabilitySumInsured")
    private String     paTotaldisabilitySumInsured ;
	
	@JsonProperty("PaMedicalSuminsured")
    private String     paMedicalSuminsured ;
	
	@JsonProperty("BuildingType")
	private String     buildingType;

	@JsonProperty("BuildingOwnerYn")
	private String     buildingOwnerYn;
	@JsonProperty("PersonalIntermediarySuminsured")
    private String     personalIntermediarySuminsured ;
	
	
	@JsonProperty("BuildingOccupationType")
    private String     buildingOccupationType ;
	@JsonProperty("WithoutInhabitantDays")
    private String    withoutInhabitantDays ;

	@JsonProperty("BuildingCondition")
    private String     buildingCondition ;
	@JsonProperty("BuildingBuildYear")
    private String    buildingBuildYear ;
	
	@JsonProperty("BuidingAreaSqm")
    private String     buidingAreaSqm ;
	@JsonProperty("BuildingSuminsured")
    private String     buildingSuminsured ;
	@JsonProperty("AllriskSumInsured")
    private String     allriskSuminsured ;
	@JsonProperty("ContentSuminsured")
    private String     contentSuminsured ;
	
	@JsonProperty("DomesticPackageYn")
    private String    domesticPackageYn;

	
	@JsonProperty("SectionId")
	private  String sectionId;	

    @JsonProperty("SectionDetails")
    private List<SectionDetails>    sectionDetails;
	

	  
}
