/*
*  Copyright (c) 2019. All right reserved
* Created on 2022-11-08 ( Date ISO 2022-11-08 - Time 16:28:23 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.maan.eway.service.impl;

import java.math.BigDecimal;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.Date;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.criteria.CriteriaBuilder;
import javax.persistence.criteria.CriteriaUpdate;
import javax.persistence.criteria.Predicate;
import javax.persistence.criteria.Root;

import org.apache.commons.lang3.StringUtils;
import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.dozer.DozerBeanMapper;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import com.maan.eway.bean.EserviceBuildingDetails;
import com.maan.eway.bean.EserviceMotorDetails;
import com.maan.eway.bean.EserviceSectionDetails;
import com.maan.eway.bean.EserviceTravelDetails;
import com.maan.eway.bean.EserviceTravelGroupDetails;
import com.maan.eway.bean.FactorRateRequestDetails;
import com.maan.eway.bean.FactorTypeDetails;
import com.maan.eway.common.req.CoverIdsReq;
import com.maan.eway.common.req.EserviceMotorDetailsSaveRes;
import com.maan.eway.common.req.EservieMotorDetailsViewRes;
import com.maan.eway.common.req.UpdateFactorRateReq;
import com.maan.eway.common.req.VehicleIdsReq;
import com.maan.eway.common.res.EserviceMotorDetailsRes;
import com.maan.eway.common.res.EserviceTravelGetRes;
import com.maan.eway.common.res.UpdateCoverRes;
import com.maan.eway.error.Error;
import com.maan.eway.repository.EServiceMotorDetailsRepository;
import com.maan.eway.repository.EServiceSectionDetailsRepository;
import com.maan.eway.repository.EserviceBuildingDetailsRepository;
import com.maan.eway.repository.EserviceTravelDetailsRepository;
import com.maan.eway.repository.EserviceTravelGroupDetailsRepository;
import com.maan.eway.repository.FactorRateRequestDetailsRepository;
import com.maan.eway.req.FactorRateDetailsGetReq;
import com.maan.eway.req.calcengine.CalcEngine;
import com.maan.eway.res.EserviceBuildingsDetailsRes;
import com.maan.eway.res.SuccessRes;
import com.maan.eway.res.calc.Cover;
import com.maan.eway.res.calc.Discount;
import com.maan.eway.res.calc.Loading;
import com.maan.eway.res.calc.Tax;
import com.maan.eway.service.CalculatorEngine;
import com.maan.eway.service.FactorRateRequestDetailsService;
/**
* <h2>FactorRateRequestDetailsServiceimpl</h2>
*/
@Service
@Transactional
public class FactorRateRequestDetailsServiceImpl implements FactorRateRequestDetailsService {

@Autowired
private FactorRateRequestDetailsRepository repository;

@Autowired
private EServiceMotorDetailsRepository eserMotorRepo;

@Autowired
private EserviceTravelDetailsRepository eserTraRepo;

@Autowired
private EserviceTravelGroupDetailsRepository eserGroupRepo;

@Autowired
private EserviceBuildingDetailsRepository eserBuildRepo;

@Autowired
private EServiceSectionDetailsRepository eserSecRepo;

@Value(value = "${motor.productId}")
private String motorProductId;

@Value(value = "${travel.productId}")
private String travelProductId;

@Value(value = "${building.productId}")
private String buildingProductId;


@Autowired
private CalculatorEngine calcEngine;

@Autowired
private FactorRateRequestDetailsRepository facRateRepo ;

@PersistenceContext
private EntityManager em;


private Logger log=LogManager.getLogger(FactorRateRequestDetailsServiceImpl.class);
/*
public FactorRateRequestDetailsServiceImpl(FactorRateRequestDetailsRepository repo) {
this.repository = repo;
}

  */
 @Override
    public FactorRateRequestDetails create(FactorRateRequestDetails d) {

       FactorRateRequestDetails entity;

        try {
            entity = repository.save(d);

        } catch (Exception ex) {
			log.error(ex);
            return null;
        }
        return entity;
    }

    
    @Override
    public FactorRateRequestDetails update(FactorRateRequestDetails d) {
        FactorRateRequestDetails c;

        try {
            c = repository.saveAndFlush(d);

        } catch (Exception ex) {
			log.error(ex);
            return null;
        }
        return c;
    }

/*
    @Override
    public FactorRateRequestDetails getOne(long id) {
        FactorRateRequestDetails t;

        try {
            t = repository.findById(id).orElse(null);

        } catch (Exception ex) {
			log.error(ex);
            return null;
        }
        return t;
    }

*/
    @Override
    public List<FactorRateRequestDetails> getAll() {
        List<FactorRateRequestDetails> lst;

        try {
            lst = repository.findAll();

        } catch (Exception ex) {
			log.error(ex);
            return Collections.emptyList();
        }
        return lst;
    }


    @Override
    public long getTotal() {
        long total;

        try {
            total = repository.count();
        } catch (Exception ex) {
            log.error(ex);
			return 0;
        }
        return total;
    }


	@Override
	@Transactional
	public SuccessRes saveFactorRateRequestDetails(EserviceMotorDetailsSaveRes req) {
		SuccessRes res = new SuccessRes();
		String successRes = "" ;
		try {
			// Find Datas
			Long factorCount = repository.countByRequestReferenceNoAndVehicleIdAndCompanyIdAndProductIdAndSectionId(req.getRequestReferenceNo(),Integer.valueOf(req.getVehicleId()), req.getInsuranceId() ,Integer.valueOf(req.getProductId()) ,Integer.valueOf(req.getSectionId()));
			List<FactorRateRequestDetails> coverIds =null;
			// Delete Old Datas
			if( factorCount > 0 ) {
				coverIds = repository.findByRequestReferenceNoAndVehicleIdAndCompanyIdAndProductIdAndSectionIdOrderByCoverIdAsc(req.getRequestReferenceNo(),Integer.valueOf(req.getVehicleId())
						, req.getInsuranceId() ,Integer.valueOf(req.getProductId()) ,Integer.valueOf(req.getSectionId()) );				
				
				repository.deleteByRequestReferenceNoAndVehicleIdAndCompanyIdAndProductIdAndSectionId(req.getRequestReferenceNo(),Integer.valueOf(req.getVehicleId())
						, req.getInsuranceId() ,Integer.valueOf(req.getProductId()) ,Integer.valueOf(req.getSectionId()) );
			}
			
			// Save New Details
			successRes = saveNewFactorRateRequestDetails(req,coverIds);
			
			res.setResponse(successRes);
			res.setSuccessId(req.getRequestReferenceNo());
			
		} catch(Exception e){
			e.printStackTrace();
			log.info("Log Details" + e.getMessage());
			return null;
			
		}return res;
	}

	
	public String saveNewFactorRateRequestDetails(EserviceMotorDetailsSaveRes req, List<FactorRateRequestDetails> coverIds) {
		String successRes = "Saved Successfully" ;
		DozerBeanMapper dozerMapper = new DozerBeanMapper(); 
		String pattern = "#####0.00";
		DecimalFormat df = new DecimalFormat(pattern);
		try {
			Double premiumLc = 0D;
			Double premiumFc = 0D;
			Double overAllPremiumLc = 0D;
			Double overAllPremiumFc = 0D;
			for ( Cover coverData  : req.getCoverList()  ) {
				
				if( coverData.getIsSubCover().equalsIgnoreCase("N") ) {
					// Save Cover Details
					FactorRateRequestDetails saveCover = new FactorRateRequestDetails(); 
					
					dozerMapper.map(coverData, saveCover);
					saveCover.setRequestReferenceNo(req.getRequestReferenceNo());
					saveCover.setSubCoverId(0);
					//saveCover.setCoverId(Integer.valueOf(coverData.getCoverId()));
					saveCover.setCurrency(coverData.getCurrency());
					saveCover.setExchangeRate(coverData.getExchangeRate()==null?null : Double.valueOf(coverData.getExchangeRate().toString()));
					saveCover.setCompanyId(req.getInsuranceId());
					saveCover.setProductId(Integer.valueOf(req.getProductId()));
					saveCover.setSectionId(Integer.valueOf(req.getSectionId()));
					saveCover.setSubCoverYn( coverData.getIsSubCover());
					saveCover.setCdRefno(req.getCdRefNo());
					saveCover.setVdRefno(req.getVdRefNo());
					saveCover.setMsRefno(req.getMsrefno());	
					saveCover.setDiscLoadId(0);
					saveCover.setTaxId(0);
					saveCover.setEntryDate(new Date());			
					saveCover.setCreatedBy(req.getCreatedBy());
					saveCover.setStatus("Y");
					saveCover.setVehicleId(Integer.valueOf(req.getVehicleId()));	
					saveCover.setDependentCoverYn(coverData.getDependentCoveryn());
					saveCover.setDependentCoverId(StringUtils.isBlank(coverData.getDependentCoverId())?null :Integer.valueOf(coverData.getDependentCoverId()));
					saveCover.setIsSelected(coverData.getIsselected());
					saveCover.setPremiumAfterDiscountFc(coverData.getPremiumAfterDiscount()==null ? null : Double.valueOf(df.format( coverData.getPremiumAfterDiscount())));
					saveCover.setPremiumBeforeDiscountFc(coverData.getPremiumBeforeDiscount()==null ? null : Double.valueOf(df.format(coverData.getPremiumBeforeDiscount())));
					saveCover.setPremiumExcludedTaxFc(coverData.getPremiumExcluedTax()==null ? null : Double.valueOf(df.format(coverData.getPremiumExcluedTax())));
					saveCover.setPremiumIncludedTaxFc(coverData.getPremiumIncludedTax()==null ? null : Double.valueOf(df.format(coverData.getPremiumIncludedTax())));
					saveCover.setPremiumAfterDiscountLc(coverData.getPremiumAfterDiscountLC()==null ? null : Double.valueOf(df.format(coverData.getPremiumAfterDiscountLC())));
					saveCover.setPremiumBeforeDiscountLc(coverData.getPremiumBeforeDiscountLC()==null ? null : Double.valueOf(df.format(coverData.getPremiumBeforeDiscountLC())));
					saveCover.setPremiumExcludedTaxLc(coverData.getPremiumExcluedTaxLC()==null ? null : Double.valueOf(df.format(coverData.getPremiumExcluedTaxLC())));
					saveCover.setPremiumIncludedTaxLc(coverData.getPremiumIncludedTaxLC()==null ? null : Double.valueOf(df.format(coverData.getPremiumIncludedTaxLC())));
 					saveCover.setIsReferral(StringUtils.isBlank(coverData.getIsReferral())?"N":coverData.getIsReferral());
					saveCover.setReferralDescription(StringUtils.isBlank(coverData.getReferalDescription())?"":coverData.getReferalDescription());
					String userOpt=!"D".equals(saveCover.getIsSelected())?"N":"Y";
				/*	if(coverIds!=null && !coverIds.isEmpty()) {
						long count = coverIds.stream().filter(t-> (saveCover.getCoverId().equals(t.getCoverId()) && saveCover.getSubCoverId().equals(t.getSubCoverId()) )).count() ;
						if(count>0) userOpt="Y";
					}*/
					
					if(req.getUpdateas()==null) {
						saveCover.setUserOpt(userOpt);
						saveCover.setActualRate(coverData.getRate());
					}
						
					saveCover.setCoverBasedOn(StringUtils.isBlank(coverData.getCoverBasedOn())?"sumInsured":coverData.getCoverBasedOn());
					//Double b=coverData.getPremiumBeforeDiscountLC()==null ? 0D : Double.valueOf(df.format(coverData.getPremiumBeforeDiscountLC()));
					saveCover.setRegulSumInsured(coverData.getTiraSumInsured()==null?null:coverData.getTiraSumInsured().doubleValue());
					
//					if(coverData.getTaxes()!=null && coverData.getTaxes().size() > 0 ) {
//						saveCover.setTax1(coverData.getTaxes().get(0).getTaxAmount()==null ? null : Double.valueOf(df.format(coverData.getTaxes().get(0).getTaxAmount())) );
//						if(coverData.getTaxes().size() > 1  ) 
//						saveCover.setTax2( coverData.getTaxes().get(1).getTaxAmount()==null ? null : Double.valueOf(df.format(coverData.getTaxes().get(1).getTaxAmount())) );
//						if(coverData.getTaxes().size() > 2  ) 
//						saveCover.setTax3(coverData.getTaxes().get(2).getTaxAmount()==null ? null : Double.valueOf(df.format(coverData.getTaxes().get(2).getTaxAmount())) );
//						
//					}
					
					repository.saveAndFlush(saveCover);
					premiumLc = premiumLc + (saveCover.getPremiumExcludedTaxLc()==null ? 0D :saveCover.getPremiumExcludedTaxLc() );
					premiumFc = premiumFc + (saveCover.getPremiumExcludedTaxFc()==null ? 0D :saveCover.getPremiumExcludedTaxFc() );
					overAllPremiumLc = overAllPremiumLc + (saveCover.getPremiumIncludedTaxLc()==null ? 0D :saveCover.getPremiumIncludedTaxLc() );
					overAllPremiumFc = overAllPremiumFc + (saveCover.getPremiumIncludedTaxFc()==null ? 0D :saveCover.getPremiumIncludedTaxFc() );
					
					Map<String,Object>  primaryKeys = new HashMap<String,Object>();
					primaryKeys.put("RefNo" , req.getRequestReferenceNo());
					primaryKeys.put("CreatedBy" , req.getCreatedBy() );
					primaryKeys.put("InsuranceId" ,req.getInsuranceId());
					primaryKeys.put("ProductId" ,req.getProductId());
					primaryKeys.put("SectionId" ,req.getSectionId());
					primaryKeys.put("SubCoverYn" ,coverData.getIsSubCover());
					primaryKeys.put("VehId" ,req.getVehicleId());
					primaryKeys.put("CdRefNo" ,req.getCdRefNo());
					primaryKeys.put("VdRefNo" ,req.getVdRefNo());
					primaryKeys.put("MsRefNo" ,req.getMsrefno());	
					
					
					// Save Discount Or Promo Cover
					if( coverData.getDiscounts()!=null && coverData.getDiscounts().size() > 0 ) {
						
						successRes  = 	saveDiscountOrPromoRates( primaryKeys ,coverData ,   coverData.getDiscounts()  ) ;	
					}
					// Tax
					if(coverData.getTaxes()!=null && coverData.getTaxes().size() > 0 ) {
						successRes  =  saveTaxes(primaryKeys ,coverData ,   coverData.getTaxes()  ) ;
					}
					
					// Loginds
					if(coverData.getLoadings()!=null && coverData.getLoadings().size() > 0 ) {
						successRes  =  saveLoadings(primaryKeys ,coverData ,   coverData.getLoadings()  ) ;
					}
					
					
				} else {
					// Save SubCover Details
					for ( Cover subCoverData : coverData.getSubcovers() ) {
						// Save Cover Details
						FactorRateRequestDetails saveSubCover = new FactorRateRequestDetails(); 
						
						dozerMapper.map(subCoverData, saveSubCover);
						saveSubCover.setRequestReferenceNo(req.getRequestReferenceNo());
						saveSubCover.setCompanyId(req.getInsuranceId());
						saveSubCover.setProductId(Integer.valueOf(req.getProductId()));
						saveSubCover.setSectionId(Integer.valueOf(req.getSectionId()));
						saveSubCover.setSubCoverYn( coverData.getIsSubCover());
						saveSubCover.setCurrency(subCoverData.getCurrency());
						saveSubCover.setExchangeRate(subCoverData.getExchangeRate()==null?null : Double.valueOf(subCoverData.getExchangeRate().toString()));
						saveSubCover.setCdRefno(req.getCdRefNo());
						saveSubCover.setVdRefno(req.getVdRefNo());
						saveSubCover.setMsRefno(req.getMsrefno());	
						saveSubCover.setDiscLoadId(0);
						saveSubCover.setTaxId(0);
						saveSubCover.setEntryDate(new Date());			
						saveSubCover.setCreatedBy(req.getCreatedBy());
						saveSubCover.setStatus("Y");
						saveSubCover.setVehicleId(Integer.valueOf(req.getVehicleId()));		
						saveSubCover.setDependentCoverYn(subCoverData.getDependentCoveryn());
						saveSubCover.setDependentCoverId(StringUtils.isBlank(subCoverData.getDependentCoverId())?null :Integer.valueOf(subCoverData.getDependentCoverId()));	
						saveSubCover.setIsSelected(subCoverData.getIsselected());
						saveSubCover.setPremiumAfterDiscountFc(subCoverData.getPremiumAfterDiscount()==null ? null : Double.valueOf(df.format(subCoverData.getPremiumAfterDiscount())));
						saveSubCover.setPremiumBeforeDiscountFc(subCoverData.getPremiumBeforeDiscount()==null ? null : Double.valueOf(df.format(subCoverData.getPremiumBeforeDiscount())));
						saveSubCover.setPremiumExcludedTaxFc(subCoverData.getPremiumExcluedTax()==null ? null : Double.valueOf(df.format(subCoverData.getPremiumExcluedTax())));
						saveSubCover.setPremiumIncludedTaxFc(subCoverData.getPremiumIncludedTax()==null ? null : Double.valueOf(df.format(subCoverData.getPremiumIncludedTax())));
						saveSubCover.setPremiumAfterDiscountLc(subCoverData.getPremiumAfterDiscountLC()==null ? null : Double.valueOf(df.format(subCoverData.getPremiumAfterDiscountLC())));
						saveSubCover.setPremiumBeforeDiscountLc(subCoverData.getPremiumBeforeDiscountLC()==null ? null : Double.valueOf(df.format(subCoverData.getPremiumBeforeDiscountLC())));
						saveSubCover.setPremiumExcludedTaxLc(subCoverData.getPremiumExcluedTaxLC()==null ? null : Double.valueOf(df.format(subCoverData.getPremiumExcluedTaxLC())));
						saveSubCover.setPremiumIncludedTaxLc(subCoverData.getPremiumIncludedTaxLC()==null ? null : Double.valueOf(df.format(subCoverData.getPremiumIncludedTaxLC())));
						saveSubCover.setIsReferral(StringUtils.isBlank(subCoverData.getIsReferral())?"N":subCoverData.getIsReferral());
						saveSubCover.setReferralDescription(StringUtils.isBlank(coverData.getReferalDescription())?"":coverData.getReferalDescription());
						saveSubCover.setRegulSumInsured(subCoverData.getTiraSumInsured()==null?null:subCoverData.getTiraSumInsured().doubleValue());
						
//						if(subCoverData.getTaxes()!=null && subCoverData.getTaxes().size() > 0 ) {
//							saveSubCover.setTax1(subCoverData.getTaxes().get(0).getTaxAmount()==null ? null : Double.valueOf(df.format(subCoverData.getTaxes().get(0).getTaxAmount())) );
//							if(coverData.getTaxes().size() > 1  ) 
//								saveSubCover.setTax2( subCoverData.getTaxes().get(1).getTaxAmount()==null ? null : Double.valueOf(df.format(subCoverData.getTaxes().get(1).getTaxAmount())) );
//							if(coverData.getTaxes().size() > 2  ) 
//								saveSubCover.setTax3(subCoverData.getTaxes().get(2).getTaxAmount()==null ? null : Double.valueOf(df.format(subCoverData.getTaxes().get(2).getTaxAmount())) );
//						}
						String userOpt=!"D".equals(saveSubCover.getIsSelected())?"N":"Y";
						/*if(coverIds!=null && !coverIds.isEmpty()) {
							long count = coverIds.stream().filter(t-> (saveSubCover.getCoverId().equals(t.getCoverId()) && saveSubCover.getSubCoverId().equals(t.getSubCoverId()) )).count() ;
							if(count>0) userOpt="Y";
						}*/
						saveSubCover.setUserOpt(userOpt);
						if(req.getUpdateas()==null) {
							saveSubCover.setUserOpt(userOpt);
							saveSubCover.setActualRate(coverData.getRate());
						}
						///Double b=subCoverData.getPremiumBeforeDiscountLC()==null ? 0D : Double.valueOf(df.format(subCoverData.getPremiumBeforeDiscountLC()));
						saveSubCover.setRegulSumInsured(subCoverData.getTiraSumInsured()==null?null:subCoverData.getTiraSumInsured().doubleValue());

						saveSubCover.setCoverBasedOn(StringUtils.isBlank(coverData.getCoverBasedOn())?"sumInsured":coverData.getCoverBasedOn());
						
						premiumLc = premiumLc + (saveSubCover.getPremiumExcludedTaxLc()==null ? 0D :saveSubCover.getPremiumExcludedTaxLc() );
						premiumFc = premiumFc + (saveSubCover.getPremiumExcludedTaxFc()==null ? 0D :saveSubCover.getPremiumExcludedTaxFc() );
						overAllPremiumLc = overAllPremiumLc + (saveSubCover.getPremiumIncludedTaxLc()==null ? 0D :saveSubCover.getPremiumIncludedTaxLc() );
						overAllPremiumFc = overAllPremiumFc + (saveSubCover.getPremiumIncludedTaxFc()==null ? 0D :saveSubCover.getPremiumIncludedTaxFc() );
					
						repository.saveAndFlush(saveSubCover);
						Map<String,Object>  primaryKeys = new HashMap<String,Object>();
						primaryKeys.put("RefNo" , req.getRequestReferenceNo());
						primaryKeys.put("CreatedBy" , req.getCreatedBy() );
						primaryKeys.put("InsuranceId" ,req.getInsuranceId());
						primaryKeys.put("ProductId" ,req.getProductId());
						primaryKeys.put("SectionId" ,req.getSectionId());
						primaryKeys.put("SubCoverYn" ,coverData.getIsSubCover());
						primaryKeys.put("VehId" ,req.getVehicleId());
						primaryKeys.put("CdRefNo" ,req.getCdRefNo());
						primaryKeys.put("VdRefNo" ,req.getVdRefNo());
						primaryKeys.put("MsRefNo" ,req.getMsrefno());	
						// Save Discount Cover Or Promo Cover
						if( subCoverData.getDiscounts()!=null && subCoverData.getDiscounts().size() > 0 ) {
							successRes  = 	saveDiscountOrPromoRates( primaryKeys ,subCoverData ,   subCoverData.getDiscounts()  ) ;
						}
						
						 
						// Tax
						if(subCoverData.getTaxes()!=null && subCoverData.getTaxes().size() > 0 ) {
							successRes  =  saveTaxes(primaryKeys ,subCoverData ,   subCoverData.getTaxes()  ) ;
						}
						
						// Loginds
						if(coverData.getLoadings()!=null && coverData.getLoadings().size() > 0 ) {
							successRes  =  saveLoadings(primaryKeys ,subCoverData ,   subCoverData.getLoadings()  ) ;
						}	
					}
				}
				
				// Update Motor Premium
				if(   req.getProductId().equalsIgnoreCase(motorProductId)) {
					EserviceMotorDetails findData =   eserMotorRepo.findByRequestReferenceNoAndRiskId(req.getRequestReferenceNo()  ,Integer.valueOf(req.getVehicleId()));
					findData.setActualPremiumLc(premiumLc ==null ? null :Double.valueOf(df.format(premiumLc )));
					findData.setActualPremiumFc(premiumFc ==null ? null :Double.valueOf(df.format(premiumFc )));
					findData.setOverallPremiumLc(overAllPremiumLc ==null ? null :Double.valueOf(df.format(overAllPremiumLc)));
					findData.setOverallPremiumFc(overAllPremiumFc ==null ? null :Double.valueOf(df.format(overAllPremiumFc)));
					
					eserMotorRepo.save(findData);
					
				// Update  Travle PRemium
				} else if(   req.getProductId().equalsIgnoreCase(travelProductId)) {
					
					// Update Group Premium
					EserviceTravelGroupDetails findData =eserGroupRepo.findByRequestReferenceNoAndGroupId(req.getRequestReferenceNo() ,Integer.valueOf(req.getVehicleId()) ); 
					findData.setActualPremiumLc(premiumLc ==null ? null :Double.valueOf(df.format(premiumLc )));
					findData.setActualPremiumFc(premiumFc ==null ? null :Double.valueOf(df.format(premiumFc )));
					findData.setOverallPremiumLc(overAllPremiumLc ==null ? null :Double.valueOf(df.format(overAllPremiumLc)));
					findData.setOverallPremiumFc(overAllPremiumFc ==null ? null :Double.valueOf(df.format(overAllPremiumFc)));
					eserGroupRepo.save(findData);
					
					List<EserviceTravelGroupDetails> findAll = eserGroupRepo.findByRequestReferenceNoOrderByGroupIdAsc(req.getRequestReferenceNo() );
					
					
					// Update OverAll Premium
					premiumFc = findAll.stream().filter( o -> o.getActualPremiumFc()!=null && o.getActualPremiumFc().doubleValue() > 0D ).mapToDouble( o ->   o.getActualPremiumFc()  ).sum();
					premiumLc = findAll.stream().filter( o -> o.getActualPremiumLc()!=null && o.getActualPremiumLc().doubleValue() > 0D ).mapToDouble( o ->   o.getActualPremiumLc()  ).sum();
					overAllPremiumFc = findAll.stream().filter( o -> o.getOverallPremiumFc()!=null && o.getOverallPremiumFc().doubleValue() > 0D ).mapToDouble( o ->   o.getOverallPremiumFc()  ).sum();
					overAllPremiumLc = findAll.stream().filter( o -> o.getOverallPremiumLc()!=null && o.getOverallPremiumLc().doubleValue() > 0D ).mapToDouble( o ->   o.getOverallPremiumLc()  ).sum();
					
					//Update TRavel Premium
					EserviceTravelDetails traData = eserTraRepo.findByRequestReferenceNo(req.getRequestReferenceNo());
					traData.setActualPremiumLc(premiumLc ==null ? null :Double.valueOf(df.format(premiumLc )));
					traData.setActualPremiumFc(premiumFc ==null ? null :Double.valueOf(df.format(premiumFc )));
					traData.setOverallPremiumLc(overAllPremiumLc ==null ? null :Double.valueOf(df.format(overAllPremiumLc)));
					traData.setOverallPremiumFc(overAllPremiumFc ==null ? null :Double.valueOf(df.format(overAllPremiumFc)));
					eserTraRepo.save(traData);
					
				}
				
				
			}
		} catch(Exception e){
			e.printStackTrace();
			log.info("Log Details" + e.getMessage());
			return null;
			
		}
		return successRes;
	}
	



	public String saveTaxes(Map<String,Object>  primaryKeys ,  Cover coverReq , List<Tax> taxes  ) {
		String res = "Saved Successfully";
		DozerBeanMapper dozerMapper = new DozerBeanMapper();
		String pattern = "#####0.00";
		DecimalFormat df = new DecimalFormat(pattern);
		try {
			for (Tax tax :  taxes ) {
				FactorRateRequestDetails saveTax = new FactorRateRequestDetails();
				dozerMapper.map(coverReq, saveTax);
				saveTax.setRequestReferenceNo(primaryKeys.get("RefNo").toString() );
				saveTax.setCoverName(coverReq.getCoverName());
				saveTax.setCoverDesc(coverReq.getCoverDesc());
				saveTax.setCurrency(coverReq.getCurrency());
				saveTax.setExchangeRate(coverReq.getExchangeRate()==null?null : Double.valueOf(coverReq.getExchangeRate().toString()));
				saveTax.setCompanyId(primaryKeys.get("InsuranceId").toString());
				saveTax.setProductId(Integer.valueOf(primaryKeys.get("ProductId").toString()));
				saveTax.setCoverageType("T");
				saveTax.setSectionId(Integer.valueOf(primaryKeys.get("SectionId").toString()));
				saveTax.setSubCoverYn( primaryKeys.get("SubCoverYn").toString());
				saveTax.setVehicleId(Integer.valueOf(primaryKeys.get("VehId").toString()));	
				saveTax.setCdRefno( primaryKeys.get("CdRefNo").toString());
				saveTax.setVdRefno( primaryKeys.get("VdRefNo").toString());
				saveTax.setMsRefno( primaryKeys.get("MsRefNo").toString());	
				saveTax.setEntryDate(new Date());			
				saveTax.setCreatedBy(primaryKeys.get("CreatedBy")==null?"":primaryKeys.get("CreatedBy").toString());
				saveTax.setSubCoverId(StringUtils.isBlank(coverReq.getSubCoverId()) ?0 : Integer.valueOf(coverReq.getSubCoverId()) );
				saveTax.setCoverId(Integer.valueOf(coverReq.getCoverId()));
				saveTax.setStatus("Y");
				saveTax.setIsSelected(coverReq.getIsselected());
				saveTax.setDiscLoadId(0);
				saveTax.setTaxAmount(tax.getTaxAmount()==null?null :Double.valueOf(tax.getTaxAmount().toString()));
				saveTax.setTaxCalcType(tax.getCalcType());
				saveTax.setTaxDesc(tax.getTaxDesc());
				saveTax.setTaxExemptType(tax.getTaxExemptType());
				saveTax.setTaxExemptCode(tax.getTaxExemptCode());
				saveTax.setTaxId(tax.getTaxId()==null?null : Integer.valueOf(tax.getTaxId()) );
				saveTax.setTaxRate(tax.getTaxRate()==null?null :Double.valueOf(tax.getTaxRate().toString()) );
				saveTax.setIsTaxExtempted(tax.getIsTaxExempted());
				
				repository.saveAndFlush(saveTax);
				
			}
			res = "Success" ;
		} catch(Exception e){
			e.printStackTrace();
			log.info("Log Details" + e.getMessage());
			res = "Failed";
			return res;
			
		}return res;
	}
	
	public String saveLoadings(Map<String,Object>  primaryKeys ,  Cover coverReq , List<Loading> lodings  ) {
		String res = "Saved Successfully";
		DozerBeanMapper dozerMapper = new DozerBeanMapper();
		String pattern = "#####0.00";
		DecimalFormat df = new DecimalFormat(pattern);
		try {
			for (Loading lod :  lodings ) {
				FactorRateRequestDetails saveLod = new FactorRateRequestDetails();
				dozerMapper.map(coverReq, lod);
				saveLod.setRequestReferenceNo(primaryKeys.get("RefNo").toString() );
				saveLod.setCoverName(lod.getLoadingDesc());
				saveLod.setCoverDesc(lod.getLoadingDesc());
				saveLod.setCurrency(coverReq.getCurrency());
				saveLod.setExchangeRate(coverReq.getExchangeRate()==null?null : Double.valueOf(coverReq.getExchangeRate().toString()));
				saveLod.setCompanyId(primaryKeys.get("InsuranceId").toString());
				saveLod.setProductId(Integer.valueOf(primaryKeys.get("ProductId").toString()));
				saveLod.setSectionId(Integer.valueOf(primaryKeys.get("SectionId").toString()));
				saveLod.setSubCoverYn( primaryKeys.get("SubCoverYn").toString());
				saveLod.setVehicleId(Integer.valueOf(primaryKeys.get("VehId").toString()));	
				saveLod.setCdRefno( primaryKeys.get("CdRefNo").toString());
				saveLod.setVdRefno( primaryKeys.get("VdRefNo").toString());
				saveLod.setMsRefno( primaryKeys.get("MsRefNo").toString());	
				saveLod.setEntryDate(new Date());			
				saveLod.setCreatedBy(primaryKeys.get("CreatedBy").toString());
				saveLod.setSubCoverId(StringUtils.isBlank(coverReq.getSubCoverId()) ?0 : Integer.valueOf(coverReq.getSubCoverId()) );
				saveLod.setCoverId(Integer.valueOf(coverReq.getCoverId()));
				saveLod.setStatus("Y");
				saveLod.setIsSelected(coverReq.getIsselected());
				saveLod.setCoverageType("L");
				
				// Factor
				saveLod.setFactorTypeId(lod.getFactorTypeId()==null?null:Double.valueOf(lod.getFactorTypeId()));
				saveLod.setMinimumPremium(lod.getLoadingAmount()==null?null:Double.valueOf(lod.getLoadingAmount().toString()));
				saveLod.setPremiumIncludedTaxFc(lod.getMaxAmount()==null?null:Double.valueOf(lod.getMaxAmount().toString()));
				saveLod.setPremiumIncludedTaxFc(lod.getMaxAmount()==null?null:Double.valueOf(lod.getMaxAmount().toString()));
				saveLod.setRate(lod.getLoadingRate()==null?null:Double.valueOf(lod.getLoadingRate()));
			//	saveLod.setLodingSubcoverId(lod.getSubCoverId()==null?null:Integer.valueOf(lod.getSubCoverId()));
				saveLod.setDiscLoadId(lod.getLoadingId()==null?null:Integer.valueOf(lod.getLoadingId()));
				saveLod.setDependentCoverYn("Y");
				saveLod.setDependentCoverId(lod.getLoadingforId()==null?null:Integer.valueOf(lod.getLoadingforId()));
				saveLod.setCalcType(lod.getLoadingCalcType());
				saveLod.setCoverName(lod.getLoadingDesc());
				saveLod.setCoverDesc(lod.getLoadingDesc());
				saveLod.setTaxId(0);
				saveLod.setPremiumAfterDiscountFc(lod.getLoadingAmount()==null ? null : Double.valueOf(df.format(lod.getLoadingAmount())));
				saveLod.setPremiumBeforeDiscountFc(lod.getLoadingAmount()==null ? null : Double.valueOf(df.format(lod.getLoadingAmount())));
				saveLod.setPremiumExcludedTaxFc(lod.getLoadingAmount()==null ? null : Double.valueOf(df.format(lod.getLoadingAmount())));
				saveLod.setPremiumIncludedTaxFc(lod.getLoadingAmount()==null ? null : Double.valueOf(df.format(lod.getLoadingAmount())));
				
				
				repository.saveAndFlush(saveLod);
				
			}
			res = "Success" ;
		} catch(Exception e){
			e.printStackTrace();
			log.info("Log Details" + e.getMessage());
			res = "Failed";
			return res;
			
		}return res;
	}
	
	public String saveDiscountOrPromoRates(Map<String,Object>  primaryKeys ,  Cover coverReq , List<Discount> discounts ) {
		String res = "Saved Successfully";
		DozerBeanMapper dozerMapper = new DozerBeanMapper();
		String pattern = "#####0.00";
		DecimalFormat df = new DecimalFormat(pattern);
		try {
			for (Discount disc :  discounts ) {
				FactorRateRequestDetails saveDiscounts = new FactorRateRequestDetails();
				dozerMapper.map(coverReq, saveDiscounts);
				saveDiscounts.setRequestReferenceNo(primaryKeys.get("RefNo").toString() );
				saveDiscounts.setDiscLoadId(Integer.valueOf(disc.getDiscountId()));
				saveDiscounts.setCoverName(disc.getDiscountDesc());
				saveDiscounts.setCoverDesc(disc.getDiscountDesc());
				saveDiscounts.setCurrency(coverReq.getCurrency());
				saveDiscounts.setExchangeRate(coverReq.getExchangeRate()==null?null : Double.valueOf(coverReq.getExchangeRate().toString()));
				saveDiscounts.setCompanyId(primaryKeys.get("InsuranceId").toString());
				saveDiscounts.setProductId(Integer.valueOf(primaryKeys.get("ProductId").toString()));
				saveDiscounts.setSectionId(Integer.valueOf(primaryKeys.get("SectionId").toString()));
				saveDiscounts.setSubCoverYn( primaryKeys.get("SubCoverYn").toString());
				saveDiscounts.setVehicleId(Integer.valueOf(primaryKeys.get("VehId").toString()));	
				saveDiscounts.setCdRefno( primaryKeys.get("CdRefNo").toString());
				saveDiscounts.setVdRefno( primaryKeys.get("VdRefNo").toString());
				saveDiscounts.setMsRefno( primaryKeys.get("MsRefNo").toString());	
				saveDiscounts.setEntryDate(new Date());			
				saveDiscounts.setCreatedBy(primaryKeys.get("CreatedBy").toString());
				saveDiscounts.setSubCoverId(StringUtils.isBlank(coverReq.getSubCoverId()) ?0 : Integer.valueOf(coverReq.getSubCoverId()) );
				saveDiscounts.setStatus("Y");
				saveDiscounts.setCoverageType(disc.getCoverAgeType() );
				saveDiscounts.setMinimumPremium(disc.getMaxAmount()==null ? null : Double.valueOf(disc.getMaxAmount().toString()));
				saveDiscounts.setSumInsured(null);
				saveDiscounts.setRate(Double.valueOf(disc.getDiscountRate()));
				saveDiscounts.setPremiumAfterDiscountFc(disc.getDiscountAmount()==null ? null : Double.valueOf(df.format(disc.getDiscountAmount())));
				saveDiscounts.setPremiumBeforeDiscountFc(disc.getDiscountAmount()==null ? null : Double.valueOf(df.format(disc.getDiscountAmount())));
				saveDiscounts.setPremiumExcludedTaxFc(disc.getDiscountAmount()==null ? null : Double.valueOf(df.format(disc.getDiscountAmount())));
				saveDiscounts.setPremiumIncludedTaxFc(disc.getDiscountAmount()==null ? null : Double.valueOf(df.format(disc.getDiscountAmount())));
				saveDiscounts.setDependentCoverYn("Y");
				saveDiscounts.setDependentCoverId(saveDiscounts.getCoverId());
				saveDiscounts.setFactorTypeId(StringUtils.isBlank(disc.getFactorTypeId())?null :Double.valueOf(disc.getFactorTypeId()) );
				saveDiscounts.setIsSelected(coverReq.getIsselected() );
				saveDiscounts.setCalcType(saveDiscounts.getCalcType());
				saveDiscounts.setTaxId(0);
				
				
				repository.saveAndFlush(saveDiscounts);
				
			}
			res = "Success" ;
		} catch(Exception e){
			e.printStackTrace();
			log.info("Log Details" + e.getMessage());
			res = "Failed";
			return res;
			
		}return res;
	}
	
	@Override
	public List<EservieMotorDetailsViewRes>  getFactorRateRequestDetails(FactorRateDetailsGetReq req) {
		List<EservieMotorDetailsViewRes>  resList = new ArrayList<EservieMotorDetailsViewRes>();
		DozerBeanMapper dozerMapper = new DozerBeanMapper();
		
		try {
			// Find Datas
			
			List<FactorRateRequestDetails> findCovers = repository.findByRequestReferenceNoOrderByVehicleIdAsc(req.getRequestReferenceNo());
		
			if( req.getProductId().equalsIgnoreCase(motorProductId) ) {
				// Motor Product Details
				List<EserviceMotorDetails>    motorDatas = eserMotorRepo.findByRequestReferenceNo(req.getRequestReferenceNo());
						
				for (EserviceMotorDetails mot :  motorDatas) {
					List<FactorRateRequestDetails> filterVehicleCovers =  findCovers.stream().filter( o -> o.getVehicleId().equals(mot.getRiskId()) &&
							o.getCompanyId().equals(mot.getCompanyId()) 
							&& o.getProductId().toString().equals(mot.getProductId())
							&& o.getSectionId().toString().equals(mot.getSectionId()) ).collect(Collectors.toList());
					Map<Integer,List<FactorRateRequestDetails>> groupByCover = filterVehicleCovers.stream().collect(Collectors.groupingBy(FactorRateRequestDetails :: getCoverId));			
					
					List<Cover> coverListRes = 	getCoversList(groupByCover);
					
					
					// Response 
					EservieMotorDetailsViewRes res = new EservieMotorDetailsViewRes();
					dozerMapper.map(mot,res);
					res.setActualPremiumFc(mot.getActualPremiumFc()==null?"":mot.getActualPremiumFc().toString());
					res.setActualPremiumLc(mot.getActualPremiumLc()==null?"":mot.getActualPremiumLc().toString());
					res.setBranchCode(mot.getBranchCode());
					res.setCdRefNo(filterVehicleCovers.size() > 0 ? filterVehicleCovers.get(0).getCdRefno() : "");
					res.setCreatedBy(mot.getCreatedBy());
					res.setCurrency(mot.getCurrency());
					res.setCustomerReferenceNo(mot.getCustomerReferenceNo());
					res.setExchangeRate(mot.getExchangeRate()==null?"":mot.getExchangeRate().toString());
					res.setInsuranceId(mot.getCompanyId());
					res.setMsrefno(filterVehicleCovers.size() > 0 ?filterVehicleCovers.get(0).getMsRefno(): "");
					res.setOverallPremiumFc(mot.getOverallPremiumFc()==null?"":mot.getOverallPremiumFc().toString());
					res.setOverallPremiumLc(mot.getOverallPremiumLc()==null?"":mot.getOverallPremiumLc().toString());
					res.setPolicyStartDate(mot.getPolicyStartDate());
					res.setPolicyEndDate(mot.getPolicyEndDate());
					res.setProductId(mot.getProductId());
					res.setRequestReferenceNo(mot.getRequestReferenceNo());
					res.setSectionId(mot.getSectionId());
					res.setVdRefNo(filterVehicleCovers.size() > 0 ?filterVehicleCovers.get(0).getVdRefno(): "");
					res.setVehicleId(mot.getRiskId().toString());
					res.setHavepromocode(mot.getHavepromocode());
					res.setPromocode(mot.getPromocode());
					res.setGroupId(1);
					res.setGroupMember(0);
					res.setCoverList(coverListRes);
					Object riskDetails = new Object();
					EserviceMotorDetailsRes  motorRes = new EserviceMotorDetailsRes();
					dozerMapper.map(mot, motorRes);
					riskDetails = motorRes ;
					res.setRiskDetails(riskDetails);
					resList.add(res);
					
					
				}
			} else if( req.getProductId().equalsIgnoreCase(travelProductId) ) {
				// Travel Product Details
				List<EserviceTravelGroupDetails>    travelDatas = eserGroupRepo.findByRequestReferenceNoOrderByGroupIdAsc(req.getRequestReferenceNo());
				EserviceTravelDetails travelData = eserTraRepo.findByRequestReferenceNo(req.getRequestReferenceNo());
				for (EserviceTravelGroupDetails tra :  travelDatas) {
					List<FactorRateRequestDetails> filterVehicleCovers =  findCovers.stream().filter( o -> o.getVehicleId().equals(tra.getGroupId()) &&
							o.getCompanyId().equals(travelData.getCompanyId()) 
							&& o.getProductId().toString().equals(travelData.getProductId())
							&& o.getSectionId().toString().equals(travelData.getSectionId())
							
							).collect(Collectors.toList());
					Map<Integer,List<FactorRateRequestDetails>> groupByCover = filterVehicleCovers.stream().collect(Collectors.groupingBy(FactorRateRequestDetails :: getCoverId));			
					
					List<Cover> coverListRes = 	getCoversList(groupByCover);
					
					
					// Response 
					EservieMotorDetailsViewRes res = new EservieMotorDetailsViewRes();
					dozerMapper.map(tra,res);
					res.setActualPremiumFc(tra.getActualPremiumFc()==null?"":tra.getActualPremiumFc().toString());
					res.setActualPremiumLc(tra.getActualPremiumLc()==null?"":tra.getActualPremiumLc().toString());
					res.setBranchCode(tra.getBranchCode());
					res.setCdRefNo(filterVehicleCovers.size() > 0 ? filterVehicleCovers.get(0).getCdRefno() : "");
					res.setCreatedBy(tra.getCreatedBy());
					res.setCurrency(travelData.getCurrency());
					res.setCustomerReferenceNo(travelData.getCustomerReferenceNo());
					res.setExchangeRate(travelData.getExchangeRate()==null?"":travelData.getExchangeRate().toString());
					res.setInsuranceId(tra.getCompanyId());
					res.setMsrefno(filterVehicleCovers.size() > 0 ?filterVehicleCovers.get(0).getMsRefno(): "");
					res.setOverallPremiumFc(tra.getOverallPremiumFc()==null?"":tra.getOverallPremiumFc().toString());
					res.setOverallPremiumLc(tra.getOverallPremiumLc()==null?"":tra.getOverallPremiumLc().toString());
					res.setPolicyStartDate(travelData.getTravelStartDate());
					res.setPolicyEndDate(travelData.getTravelEndDate());
					res.setProductId(tra.getProductId());
					res.setRequestReferenceNo(tra.getRequestReferenceNo());
					res.setSectionId(travelData.getSectionId());
					res.setVdRefNo(filterVehicleCovers.size() > 0 ?filterVehicleCovers.get(0).getVdRefno(): "");
					res.setVehicleId(tra.getGroupId().toString());
					res.setHavepromocode(travelData.getHavepromocode());
					res.setPromocode(travelData.getPromocode());
					res.setGroupId(tra.getGroupId()==null?null:tra.getGroupId());
					res.setGroupMember(tra.getGrouppMembers()==null?null:tra.getGrouppMembers() );
					res.setCoverList(coverListRes);
					
					Object riskDetails = new Object();
					EserviceTravelGetRes  travelRes = new EserviceTravelGetRes();
					dozerMapper.map(travelData, travelRes);
					travelRes.setTotalPassengers(tra.getGrouppMembers().toString());
					travelRes.setTravelId(tra.getGroupId().toString());
					riskDetails = travelRes ;
					res.setRiskDetails(riskDetails);
					resList.add(res);
					
					
				}
			}   else if( req.getProductId().equalsIgnoreCase(buildingProductId) ) {
				// Building Product Details
				List<EserviceSectionDetails>    sectionDatas = eserSecRepo.findByRequestReferenceNoOrderByRiskIdAsc(req.getRequestReferenceNo());
				List<EserviceBuildingDetails> buildDatas = eserBuildRepo.findByRequestReferenceNoOrderByRiskIdAsc(req.getRequestReferenceNo());
				
				for (EserviceSectionDetails sec :  sectionDatas) {
					List<FactorRateRequestDetails> filterVehicleCovers =  findCovers.stream().filter( o -> o.getVehicleId().equals(sec.getRiskId()) &&  
							o.getCompanyId().equals(sec.getCompanyId()) 
							&& o.getProductId().toString().equals(sec.getProductId()) &&
							o.getSectionId().equals(Integer.valueOf(sec.getSectionId()))
							
							).collect(Collectors.toList());
					Map<Integer,List<FactorRateRequestDetails>> groupByCover = filterVehicleCovers.stream().collect(Collectors.groupingBy(FactorRateRequestDetails :: getCoverId));			
					
					List<Cover> coverListRes = 	getCoversList(groupByCover);
					EserviceBuildingDetails buildData = buildDatas.stream().filter( o -> o.getRiskId().equals(sec.getRiskId())  ).collect(Collectors.toList()).get(0);
					
					// Response 
					EservieMotorDetailsViewRes res = new EservieMotorDetailsViewRes();
					dozerMapper.map(sec,res);
					res.setActualPremiumFc(buildData.getActualPremiumFc()==null?"":buildData.getActualPremiumFc().toString());
					res.setActualPremiumLc(buildData.getActualPremiumLc()==null?"":buildData.getActualPremiumLc().toString());
					res.setBranchCode(buildData.getBranchCode());
					res.setCdRefNo(filterVehicleCovers.size() > 0 ? filterVehicleCovers.get(0).getCdRefno() : "");
					res.setCreatedBy(sec.getCreatedBy());
					res.setCurrency(buildData.getCurrency());
					res.setCustomerReferenceNo(buildData.getCustomerReferenceNo());
					res.setExchangeRate(buildData.getExchangeRate()==null?"":buildData.getExchangeRate().toString());
					res.setInsuranceId(sec.getCompanyId());
					res.setMsrefno(filterVehicleCovers.size() > 0 ?filterVehicleCovers.get(0).getMsRefno(): "");
					res.setOverallPremiumFc(buildData.getOverallPremiumFc()==null?"":buildData.getOverallPremiumFc().toString());
					res.setOverallPremiumLc(buildData.getOverallPremiumLc()==null?"":buildData.getOverallPremiumLc().toString());
					res.setPolicyStartDate(buildData.getPolicyStartDate());
					res.setPolicyEndDate(buildData.getPolicyEndDate());
					res.setProductId(sec.getProductId());
					res.setRequestReferenceNo(sec.getRequestReferenceNo());
					res.setSectionId(sec.getSectionId());
					res.setVdRefNo(filterVehicleCovers.size() > 0 ?filterVehicleCovers.get(0).getVdRefno(): "");
					res.setVehicleId(sec.getRiskId().toString());
					res.setHavepromocode(buildData.getHavepromocode());
					res.setPromocode(buildData.getPromocode());
					res.setGroupId(buildData.getRiskId()==null?null:buildData.getRiskId());
				//	res.setGroupMember(sec.getGrouppMembers()==null?null:tra.getGrouppMembers() );
					res.setCoverList(coverListRes);
					Object riskDetails = new Object();
					EserviceBuildingsDetailsRes  buildRes = new EserviceBuildingsDetailsRes();
					dozerMapper.map(buildData, buildRes);
					riskDetails = buildRes ;
					res.setRiskDetails(riskDetails); 
					resList.add(res);
					
					
				}
			}  
		
			
		} catch(Exception e){
			e.printStackTrace();
			log.info("Log Details" + e.getMessage());
			return null;
			
		}return resList;
	}
	
	

	public synchronized List<Cover> getCoversList(Map<Integer,List<FactorRateRequestDetails>> groupByCover) {
		List<Cover>  coverListRes = new ArrayList<Cover>();
		DozerBeanMapper dozerMapper = new DozerBeanMapper();
		try {
			for ( Integer coverId : groupByCover.keySet() ) {
				List<FactorRateRequestDetails>  covers  = groupByCover.get(coverId);
				Cover coverRes = new Cover();
				
				if (covers.get(0).getSubCoverYn().equalsIgnoreCase("N") ) {
					// Get Covers
					List<FactorRateRequestDetails> filterCover = covers.stream().filter( o -> o.getDiscLoadId().equals(0) && o.getTaxId().equals(0) ).collect(Collectors.toList());
					coverRes = dozerMapper.map(filterCover.get(0), Cover.class);
					coverRes.setIsSubCover(filterCover.get(0).getSubCoverYn());
					coverRes.setDependentCoveryn(filterCover.get(0).getDependentCoverYn());
					coverRes.setDependentCoverId(filterCover.get(0).getDependentCoverId()==null?"":filterCover.get(0).getDependentCoverId().toString());
					coverRes.setPremiumExcluedTax( filterCover.get(0).getPremiumExcludedTaxFc()==null ? null : new BigDecimal(filterCover.get(0).getPremiumExcludedTaxFc()) );	
					coverRes.setPremiumAfterDiscount(filterCover.get(0).getPremiumAfterDiscountFc()==null ? null : new BigDecimal((filterCover.get(0).getPremiumAfterDiscountFc().toString())));
					coverRes.setPremiumBeforeDiscount(filterCover.get(0).getPremiumBeforeDiscountFc()==null ? null : new BigDecimal((filterCover.get(0).getPremiumBeforeDiscountFc().toString())));
					coverRes.setPremiumExcluedTax(filterCover.get(0).getPremiumExcludedTaxFc()==null ? null : new BigDecimal((filterCover.get(0).getPremiumExcludedTaxFc().toString())));
					coverRes.setPremiumIncludedTax(filterCover.get(0).getPremiumIncludedTaxFc()==null ? null : new BigDecimal((filterCover.get(0).getPremiumIncludedTaxFc().toString())));
					coverRes.setIsselected(filterCover.get(0).getIsSelected());
					coverRes.setDependentCoveryn(filterCover.get(0).getDependentCoverYn());
					coverRes.setDependentCoverId(filterCover.get(0).getDependentCoverId()==null?"": filterCover.get(0).getDependentCoverId().toString());
					coverRes.setSubCoverId(null);
					coverRes.setSubCoverDesc(null);
					coverRes.setSubCoverName(null);
					coverRes.setSectionId(filterCover.get(0).getSectionId()==null?"":filterCover.get(0).getSectionId().toString());
					coverRes.setPremiumAfterDiscount(filterCover.get(0).getPremiumAfterDiscountFc()==null ? null : new BigDecimal (filterCover.get(0).getPremiumAfterDiscountFc()));
					coverRes.setPremiumBeforeDiscount(filterCover.get(0).getPremiumBeforeDiscountFc()==null ? null : new BigDecimal (filterCover.get(0).getPremiumBeforeDiscountFc()));
					coverRes.setPremiumExcluedTax(filterCover.get(0).getPremiumExcludedTaxFc()==null ? null : new BigDecimal (filterCover.get(0).getPremiumExcludedTaxFc()));
					coverRes.setPremiumIncludedTax(filterCover.get(0).getPremiumIncludedTaxFc()==null ? null :new BigDecimal(filterCover.get(0).getPremiumIncludedTaxFc()));
					coverRes.setPremiumAfterDiscountLC(filterCover.get(0).getPremiumAfterDiscountLc()==null ? null : new BigDecimal(filterCover.get(0).getPremiumAfterDiscountLc()));
					coverRes.setPremiumBeforeDiscountLC(filterCover.get(0).getPremiumBeforeDiscountLc()==null ? null : new BigDecimal( filterCover.get(0).getPremiumBeforeDiscountLc()));
					coverRes.setPremiumExcluedTaxLC(filterCover.get(0).getPremiumExcludedTaxLc()==null ? null : new BigDecimal(filterCover.get(0).getPremiumExcludedTaxLc()));
					coverRes.setPremiumIncludedTaxLC(filterCover.get(0).getPremiumIncludedTaxLc()==null ? null :new BigDecimal (filterCover.get(0).getPremiumIncludedTaxLc()));
					coverRes.setExchangeRate(filterCover.get(0).getExchangeRate()==null?null:new BigDecimal(filterCover.get(0).getExchangeRate()));	
					
					// Discount Covers Or Promo Covers
					List<FactorRateRequestDetails> filterDiscountCover = covers.stream().filter( o -> ( ! o.getDiscLoadId().equals(0)) && (   o.getCoverageType().equalsIgnoreCase("D") || o.getCoverageType().equalsIgnoreCase("P") ) ).collect(Collectors.toList());
					
					if ( filterDiscountCover.size() > 0 ) {
						 List<Discount> discounts =  getDiscountRates(filterDiscountCover);
						 coverRes.setDiscounts(discounts);	
					}
					
					// Tax Covers
					List<FactorRateRequestDetails> filterTaxCover = covers.stream().filter( o -> (! o.getTaxId().equals(0)) &&  o.getCoverageType().equalsIgnoreCase("T")).collect(Collectors.toList());
					
					if( filterTaxCover.size() > 0 ) {
						 List<Tax> taxes = getTaxRates(filterTaxCover) ;
						 coverRes.setTaxes(taxes);	
					}
					
					// Loginds Covers
					List<FactorRateRequestDetails> filterLodingCover = covers.stream().filter( o -> ( ! o.getDiscLoadId().equals(0)) &&  o.getCoverageType().equalsIgnoreCase("L") ).collect(Collectors.toList());
					
					if( filterLodingCover.size() > 0 ) {
						 List<Loading> lodings =  getLodingCovers(filterLodingCover) ;
						 coverRes.setLoadings(lodings);	
					}
										
				} else {
					
					// Get Sub Covers
			
					List<FactorRateRequestDetails> filterCover = covers.stream().filter( o -> o.getDiscLoadId().equals(0) && o.getTaxId().equals(0) ).collect(Collectors.toList());
					 coverRes.setCoverId(filterCover.get(0).getCoverId().toString());
					 coverRes.setCalcType(filterCover.get(0).getCalcType());
					 coverRes.setCoverName(filterCover.get(0).getCoverName());
					 coverRes.setCoverDesc(filterCover.get(0).getCoverDesc());
					 coverRes.setMinimumPremium(filterCover.get(0).getMinimumPremium()==null ? null : new BigDecimal(filterCover.get(0).getMinimumPremium().toString()));
					 coverRes.setIsSubCover(filterCover.get(0).getSubCoverYn());
					 coverRes.setSumInsured(filterCover.get(0).getSumInsured()==null ? null : new BigDecimal(filterCover.get(0).getSumInsured().toString()));
					 coverRes.setRate(filterCover.get(0).getRate());
					
					List<Cover>  subCoverListRes = new ArrayList<Cover>();
					List<FactorRateRequestDetails> filterSubCover = covers.stream().filter( o -> o.getDiscLoadId().equals(0) && o.getTaxId().equals(0)).collect(Collectors.toList());
					for ( FactorRateRequestDetails subCovers : filterSubCover) {
						Cover subCoverRes = new Cover();
						subCoverRes = dozerMapper.map(subCovers, Cover.class);
						subCoverRes.setIsSubCover(filterSubCover.get(0).getSubCoverYn());
						subCoverRes.setDependentCoveryn(filterSubCover.get(0).getDependentCoverYn());
						subCoverRes.setDependentCoverId(filterSubCover.get(0).getDependentCoverId()==null?"":filterSubCover.get(0).getDependentCoverId().toString());
						subCoverRes.setPremiumExcluedTax( filterSubCover.get(0).getPremiumExcludedTaxFc()==null ? null : new BigDecimal(filterSubCover.get(0).getPremiumExcludedTaxFc()) );	
						subCoverRes.setPremiumAfterDiscount(filterSubCover.get(0).getPremiumAfterDiscountFc()==null ? null : new BigDecimal((filterSubCover.get(0).getPremiumAfterDiscountFc().toString())));
						subCoverRes.setPremiumBeforeDiscount(filterSubCover.get(0).getPremiumBeforeDiscountFc()==null ? null : new BigDecimal((filterSubCover.get(0).getPremiumBeforeDiscountFc().toString())));
						subCoverRes.setPremiumExcluedTax(filterSubCover.get(0).getPremiumExcludedTaxFc()==null ? null : new BigDecimal((filterSubCover.get(0).getPremiumExcludedTaxFc().toString())));
						subCoverRes.setPremiumIncludedTax(filterSubCover.get(0).getPremiumIncludedTaxFc()==null ? null : new BigDecimal((filterCover.get(0).getPremiumIncludedTaxFc().toString())));
						subCoverRes.setIsselected(filterSubCover.get(0).getIsSelected());
						subCoverRes.setExchangeRate(filterSubCover.get(0).getExchangeRate()==null?null:new BigDecimal(filterSubCover.get(0).getExchangeRate()));	
						subCoverRes.setSectionId(filterSubCover.get(0).getSectionId()==null?"":filterSubCover.get(0).getSectionId().toString());

						subCoverRes.setPremiumAfterDiscount(filterSubCover.get(0).getPremiumAfterDiscountFc()==null ? null : new BigDecimal (filterSubCover.get(0).getPremiumAfterDiscountFc()));
						subCoverRes.setPremiumBeforeDiscount(filterSubCover.get(0).getPremiumBeforeDiscountFc()==null ? null : new BigDecimal (filterSubCover.get(0).getPremiumBeforeDiscountFc()));
						subCoverRes.setPremiumExcluedTax(filterSubCover.get(0).getPremiumExcludedTaxFc()==null ? null : new BigDecimal (filterSubCover.get(0).getPremiumExcludedTaxFc()));
						subCoverRes.setPremiumIncludedTax(filterSubCover.get(0).getPremiumIncludedTaxFc()==null ? null :new BigDecimal(filterSubCover.get(0).getPremiumIncludedTaxFc()));
						subCoverRes.setPremiumAfterDiscountLC(filterSubCover.get(0).getPremiumAfterDiscountLc()==null ? null : new BigDecimal(filterSubCover.get(0).getPremiumAfterDiscountLc()));
						subCoverRes.setPremiumBeforeDiscountLC(filterSubCover.get(0).getPremiumBeforeDiscountLc()==null ? null : new BigDecimal( filterSubCover.get(0).getPremiumBeforeDiscountLc()));
						subCoverRes.setPremiumExcluedTaxLC(filterSubCover.get(0).getPremiumExcludedTaxLc()==null ? null : new BigDecimal(filterSubCover.get(0).getPremiumExcludedTaxLc()));
						subCoverRes.setPremiumIncludedTaxLC(filterSubCover.get(0).getPremiumIncludedTaxLc()==null ? null :new BigDecimal (filterSubCover.get(0).getPremiumIncludedTaxLc()));
						
						
						// Discount Covers Or Promo Covers
						List<FactorRateRequestDetails> filterDiscountCover = covers.stream().filter( o -> o.getCoverId().equals(subCovers.getCoverId()) && o.getSubCoverId().equals(subCovers.getSubCoverId()) && ( ! o.getDiscLoadId().equals(0)) && (   o.getCoverageType().equalsIgnoreCase("D") || o.getCoverageType().equalsIgnoreCase("P") ) ).collect(Collectors.toList());
						
						if ( filterDiscountCover.size() > 0 ) {
							 List<Discount> discounts =  getDiscountRates(filterDiscountCover);
							 subCoverRes.setDiscounts(discounts);	
						}
						
						// Tax Covers
						List<FactorRateRequestDetails> filterTaxCover = covers.stream().filter( o -> o.getCoverId().equals(subCovers.getCoverId()) && o.getSubCoverId().equals(subCovers.getSubCoverId()) && (! o.getTaxId().equals(0)) &&  o.getIsSelected().equalsIgnoreCase("T")).collect(Collectors.toList());
						
						if( filterTaxCover.size() > 0 ) {
							 List<Tax> taxes = getTaxRates(filterTaxCover) ;
							 subCoverRes.setTaxes(taxes);	
						}
						
						// Loginds Covers
						List<FactorRateRequestDetails> filterLodingCover = covers.stream().filter( o -> o.getCoverId().equals(subCovers.getCoverId()) && o.getSubCoverId().equals(subCovers.getSubCoverId()) &&  ( ! o.getDiscLoadId().equals(0)) &&  o.getIsSelected().equalsIgnoreCase("L") ).collect(Collectors.toList());
						
						if( filterLodingCover.size() > 0 ) {
							 List<Loading> lodings =  getLodingCovers(filterLodingCover) ;
							 subCoverRes.setLoadings(lodings);	
						}
						subCoverListRes.add(subCoverRes);
					}
					coverRes.setSubcovers(subCoverListRes);
				}
				coverListRes.add(coverRes);
			}
			
			coverListRes.sort(Comparator.comparing(Cover ::    getSumInsured ).reversed() );
			
		} catch(Exception e){
			e.printStackTrace();
			log.info("Log Details" + e.getMessage());
			return null;
			
		}return coverListRes;
	}
	
	public List<Discount> getDiscountRates(List<FactorRateRequestDetails> filterDiscountCover) {
		List<Discount> DiscountList = new  ArrayList<Discount>();
		try {
			for (FactorRateRequestDetails disc :  filterDiscountCover ) {
				Discount discount = new Discount();
				discount.setDiscountAmount(disc.getPremiumIncludedTaxFc()==null?new BigDecimal(0): new BigDecimal(disc.getPremiumIncludedTaxFc()));
				discount.setDiscountCalcType(disc.getCalcType());
				discount.setDiscountId(disc.getDiscLoadId().toString());
				discount.setDiscountDesc(disc.getCoverName());	
				discount.setDiscountRate(disc.getRate()==null?"0.0" :disc.getRate().toString());
				discount.setFactorTypeId(disc.getFactorTypeId()==null?"" : disc.getFactorTypeId().toString());
				discount.setMaxAmount(disc.getMinimumPremium()==null?null :new BigDecimal(disc.getMinimumPremium()));
				discount.setSubCoverId(disc.getSubCoverId().toString());
				discount.setDiscountforId(disc.getDependentCoverId()==null?null:disc.getDependentCoverId().toString());
				
				DiscountList.add(discount);
				
			}
			
		} catch(Exception e){
			e.printStackTrace();
			log.info("Log Details" + e.getMessage());
			return null;
			
		}return DiscountList;
	}
	
	
	public List<Loading> getLodingCovers(List<FactorRateRequestDetails> filterLodingCover) {
		List<Loading> LodingList = new  ArrayList<Loading>();
		try {
			for (FactorRateRequestDetails lod :  filterLodingCover ) {
				Loading loding = new Loading();
				loding.setFactorTypeId(lod.getFactorTypeId()==null?null:lod.getFactorTypeId().toString());
				loding.setLoadingAmount(lod.getMinimumPremium()==null?null:new BigDecimal(lod.getMinimumPremium()));
				loding.setLoadingCalcType(lod.getCalcType());
				loding.setLoadingDesc(lod.getCoverName());
				loding.setLoadingforId(lod.getDependentCoverId()==null?null:lod.getDependentCoverId().toString());
				loding.setLoadingId(lod.getDiscLoadId()==null?null:lod.getDiscLoadId().toString());
				loding.setLoadingRate(lod.getRate()==null?null:lod.getRate().toString());
				loding.setMaxAmount(lod.getPremiumIncludedTaxFc()==null?null:new BigDecimal(lod.getPremiumIncludedTaxFc()));
				//loding.setSubCoverId(lod.getLodingSubcoverId()==null?null:lod.getLodingSubcoverId().toString());	
				LodingList.add(loding);
			}
			
		} catch(Exception e){
			e.printStackTrace();
			log.info("Log Details" + e.getMessage());
			return null;
			
		}return LodingList;
	}
	
	public List<Tax> getTaxRates(List<FactorRateRequestDetails> filterTaxCover) {
		List<Tax> TaxList = new  ArrayList<Tax>();
		try {
			for (FactorRateRequestDetails tax :  filterTaxCover ) {
				Tax taxes = new Tax();
				taxes.setCalcType(tax.getCalcType());
				taxes.setIsTaxExempted(tax.getIsTaxExtempted());
				taxes.setTaxAmount(tax.getTaxAmount()==null?null:new BigDecimal(tax.getTaxAmount()));
				taxes.setTaxDesc(tax.getTaxDesc());
				taxes.setTaxExemptCode(tax.getTaxExemptCode());
				taxes.setTaxExemptType(tax.getTaxExemptType());
				taxes.setTaxId(tax.getTaxId()==null?null:tax.getTaxId().toString()) ;
				taxes.setTaxRate(tax.getTaxRate());
				TaxList.add(taxes);
			}
			
		} catch(Exception e){
			e.printStackTrace();
			log.info("Log Details" + e.getMessage());
			return null;
			
		}return TaxList;
	}


	@Override
	public List<Error> validateFoctorPremiumDetails(UpdateFactorRateReq req) {
		List<Error> errors = new ArrayList<Error>();
		try {
			if ( req.getCoverIdList()==null  || req.getCoverIdList().size()<=0 ) {
				errors.add(new Error("01","CoverList","Please Enter Cover List")) ;				
			} else {
				for (CoverIdsReq cov : req.getCoverIdList() ) {
					
					if (cov.getCoverId()==null   ) {
						errors.add(new Error("01","CoverIds","Please Enter Cover Id")) ;				
					}
					if (StringUtils.isBlank(cov.getSubCoverYn())  ) {
						errors.add(new Error("01","SubCoverYn","Please Select SubCover Yes/No")) ;				
					} else if (! (cov.getSubCoverYn().equalsIgnoreCase("Y") || cov.getSubCoverYn().equalsIgnoreCase("N") ) ) {
						errors.add(new Error("01","SubCoverYn","Please Select SubCover Yes/No")) ;
					} else if( cov.getSubCoverYn().equalsIgnoreCase("Y") && cov.getSubCoverId() ==null ) {
						errors.add(new Error("01","SubCoverYn","Please Enter SubCover Id")) ;
					}
					
					if (cov.getMinimumPremium()==null   ) {
						errors.add(new Error("01","MinimumPremium","Please Enter MimimumPremium")) ;				
					} else if (! cov.getMinimumPremium().matches("[0-9.]+")   ) {
						errors.add(new Error("01","MinimumPremium","Please Enter Valid MimimumPremium")) ;				
					} else if ( cov.getMinimumPremium().equalsIgnoreCase("0")   ) {
						errors.add(new Error("01","MinimumPremium","Please Enter Valid Number In MimimumPremium")) ;				
					}
					
					if (cov.getRate()==null   ) {
						errors.add(new Error("01","Rate","Please Enter Rate")) ;				
					} else if (! cov.getRate().matches("[0-9.]+")   ) {
						errors.add(new Error("01","Rate","Please Enter Valid Rate")) ;				
					} else if ( cov.getRate().equalsIgnoreCase("0")   ) {
						errors.add(new Error("01","Rate","Please Enter Valid Number In Rate")) ;				
					}
				}
			}
			
		} catch(Exception e){
			e.printStackTrace();
			log.info("Log Details" + e.getMessage());
			return null;
			
		}return errors;
	}


	@Override
	public UpdateCoverRes updateFactorRatePremiumDetails(UpdateFactorRateReq req) {
		UpdateCoverRes res = new UpdateCoverRes();
		String pattern = "#####0.00";
		DecimalFormat df = new DecimalFormat(pattern);
		try {
			String agencyCode = "";
			String branchCode = "";
			
			List<FactorRateRequestDetails> findCovers = repository.findByRequestReferenceNoAndVehicleIdAndCompanyIdAndProductIdAndSectionIdOrderByCoverIdAsc(req.getRequestReferenceNo() , req.getVehicleId() ,
					req.getCompanyId() , Integer.valueOf(req.getProductId()) , Integer.valueOf(req.getSectionId())   ) ;	
			if(   req.getProductId().equalsIgnoreCase(motorProductId)) {
				EserviceMotorDetails  findMot = eserMotorRepo.findByRequestReferenceNoAndRiskId(req.getRequestReferenceNo() , req.getVehicleId() 
						) ;
				agencyCode = findMot.getAgencyCode();
				branchCode = findMot.getBranchCode();
				
			} else if(   req.getProductId().equalsIgnoreCase(travelProductId)) {
				EserviceTravelDetails  findTra = eserTraRepo.findByRequestReferenceNoAndCompanyIdAndProductIdAndSectionId(req.getRequestReferenceNo() ,
						req.getCompanyId() , 	 req.getProductId(),req.getSectionId()  ) ;
				agencyCode = findTra.getBrokerCode();
				branchCode = findTra.getBranchCode();
			//	EserviceTravelGroupDetails  findGroup = eserGroupRepo.findByRequestReferenceNoAndTravelIdAndGroupIdAndCompanyIdAndProductIdAndSectionId(req.getRequestReferenceNo() , req.getVehicleId() ,Integer.valueOf(req.getGroupId()) ,
			//			req.getCompanyId() , 	 Integer.valueOf(req.getProductId()) , Integer.valueOf(req.getSectionId())   ) ;
				
			} else if(   req.getProductId().equalsIgnoreCase(buildingProductId)) {
				EserviceBuildingDetails    findBuild = eserBuildRepo.findByRequestReferenceNoAndRiskIdAndCompanyIdAndProductId(req.getRequestReferenceNo() , req.getVehicleId() ,
						req.getCompanyId() , 	 Integer.valueOf(req.getProductId())  ) ;
				agencyCode = findBuild.getBrokerCode();
				branchCode = findBuild.getBranchCode();
			//	EserviceBuildingSectionDetails  findBuildSec = eserBuildSecRepo.findByRequestReferenceNoAndLocationIdAndCompanyIdAndProductIdAndSectionId(req.getRequestReferenceNo() , req.getVehicleId() ,
			//			req.getCompanyId() , 	 Integer.valueOf(req.getProductId()) , Integer.valueOf(req.getSectionId())   ) ;
			}
			
			
			for (CoverIdsReq covReq :    req.getCoverIdList()  ) {
				
				if(StringUtils.isBlank(covReq.getSubCoverYn()) || covReq.getSubCoverYn().equalsIgnoreCase("N") ) {
					List<FactorRateRequestDetails> filterCover = findCovers.stream().filter( o -> o.getCoverId().equals(covReq.getCoverId()) && o.getDiscLoadId().equals(0) && o.getTaxId().equals(0)  ).collect(Collectors.toList()); 
					
					if(filterCover.size()>0 ) {
						FactorRateRequestDetails  updateCover = filterCover.get(0);
						updateCover.setMinimumPremium(Double.valueOf(df.format(Double.valueOf(covReq.getMinimumPremium()))));
						updateCover.setRate(Double.valueOf(df.format(Double.valueOf(covReq.getRate()))));
						repository.save(updateCover);
						
					}
				} else {
					List<FactorRateRequestDetails> filterSubCover = findCovers.stream().filter( o -> o.getCoverId().equals(covReq.getCoverId()) && o.getSubCoverId().equals(Integer.valueOf(covReq.getSubCoverId())) && o.getDiscLoadId().equals(0) && o.getTaxId().equals(0) ).collect(Collectors.toList());
					if(filterSubCover.size()>0 ) {
						FactorRateRequestDetails  updateSubCover = filterSubCover.get(0);
						updateSubCover.setMinimumPremium(Double.valueOf(df.format(Double.valueOf(covReq.getMinimumPremium()))));
						updateSubCover.setRate(Double.valueOf(df.format(Double.valueOf(covReq.getRate()))));
						repository.save(updateSubCover);
					}
					
				}
				
			}
			
			
			CalcEngine engine= new CalcEngine();
			engine.setAgencyCode(agencyCode);
			engine.setBranchCode(branchCode);
			engine.setCdRefNo(findCovers.get(0).getCdRefno());
			engine.setVdRefNo(findCovers.get(0).getVdRefno());
			engine.setInsuranceId(findCovers.get(0).getCompanyId());
			engine.setMsrefno(findCovers.get(0).getMsRefno());
			engine.setProductId(findCovers.get(0).getProductId().toString());
			engine.setRequestReferenceNo(findCovers.get(0).getRequestReferenceNo());
			engine.setSectionId(findCovers.get(0).getProductId().toString());
			engine.setVehicleId(findCovers.get(0).getVehicleId()+"");
			engine.setCreatedBy(findCovers.get(0).getCreatedBy());
			engine.setMsVehicleDetails(null);
			
			calcEngine.referalCalculator(engine);
			
			
			// Get Updated Covers
			findCovers = repository.findByRequestReferenceNoAndVehicleIdAndCompanyIdAndProductIdAndSectionIdOrderByCoverIdAsc(req.getRequestReferenceNo() , req.getVehicleId() ,
					req.getCompanyId() , 	 Integer.valueOf(req.getProductId()) , Integer.valueOf(req.getSectionId())   ) ;
			Map<Integer,List<FactorRateRequestDetails>> groupByCover = findCovers.stream().collect(Collectors.groupingBy(FactorRateRequestDetails :: getCoverId));			
			
			
			// Update Admin Opted COvers
			List<FactorRateRequestDetails> userOptCovers = new ArrayList<FactorRateRequestDetails>();
			
			//UPDATE
			CriteriaBuilder cb = em.getCriteriaBuilder();
			// create update
			CriteriaUpdate<FactorRateRequestDetails> update = cb.createCriteriaUpdate(FactorRateRequestDetails.class);
			// set the root class
			Root<FactorRateRequestDetails> m = update.from(FactorRateRequestDetails.class);
			// set update and where clause
			update.set("userOpt", "N");
			
			Predicate n1 = cb.equal(m.get("vehicleId"), req.getVehicleId());
			Predicate n2 = cb.equal(m.get("sectionId"), req.getSectionId());
			Predicate n3 = cb.equal(m.get("requestReferenceNo"), req.getRequestReferenceNo() );
			Predicate n4 = cb.equal(m.get("productId"),req.getProductId());
			update.where(n1,n2,n3,n4);
			// perform update
			em.createQuery(update).executeUpdate();
			
			// Covers Admin Opt
			List<FactorRateRequestDetails> covers = facRateRepo.findByRequestReferenceNoAndVehicleIdAndSectionIdOrderByVehicleIdAsc(req.getRequestReferenceNo(), req.getVehicleId(),Integer.valueOf(req.getSectionId()));			
			
			// Cover Referal Checking
			List<CoverIdsReq> coverList = req.getCoverIdList();
			for (CoverIdsReq cov : coverList) {
				if(StringUtils.isBlank(cov.getSubCoverYn()) || cov.getSubCoverYn().equalsIgnoreCase("N") ) {
					List<FactorRateRequestDetails> filterCovers = covers.stream().filter( o ->o.getSectionId().equals(Integer.valueOf(req.getSectionId())) && o.getCoverId().equals(cov.getCoverId()) ).collect(Collectors.toList());		
					userOptCovers.addAll(filterCovers);
					
				
				} else {
					List<FactorRateRequestDetails> filterSubCovers  = covers.stream().filter( o -> o.getSectionId().equals(Integer.valueOf(req.getSectionId())) && o.getCoverId().equals(cov.getCoverId()) && o.getSubCoverId().equals(Integer.valueOf(cov.getSubCoverId()))  ).collect(Collectors.toList());
					userOptCovers.addAll(filterSubCovers);
					
				}
			}
			
		
			// Update Admin Opted Covers 
			for (FactorRateRequestDetails uptCover : userOptCovers ) {
				
				uptCover.setUserOpt("Y");
				facRateRepo.save(uptCover);
			}
			
			List<Cover> coverListRes = 	getCoversList(groupByCover);
			coverListRes.sort(Comparator.comparing(Cover :: getCoverId).reversed() );
			res.setCoverList(coverListRes);
			res.setBranchCode(branchCode);
			res.setInsuranceId(findCovers.get(0).getCompanyId());
			res.setProductId(findCovers.get(0).getProductId().toString());
			res.setRequestReferenceNo(req.getRequestReferenceNo());
			res.setSectionId(findCovers.get(0).getProductId().toString());
			res.setResponse("Cover Updated Successfully");			
			
			
		} catch(Exception e){
			e.printStackTrace();
			log.info("Log Details" + e.getMessage());
			return null;
			
		}return res;
	}


	@Override
	public List<Error> validateFactorIsSelectedDetails(UpdateFactorRateReq req) {
		List<Error> errors = new ArrayList<Error>();
		try {
			if ( req.getCoverIdList()==null  || req.getCoverIdList().size()<=0 ) {
				errors.add(new Error("01","CoverList","Please Enter Cover List")) ;				
			} else {
				for (CoverIdsReq cov : req.getCoverIdList() ) {
					
					if (cov.getCoverId()==null   ) {
						errors.add(new Error("01","CoverIds","Please Enter Cover Id")) ;				
					}
					if (StringUtils.isBlank(cov.getUserOpt())  ) {
						errors.add(new Error("01","UserOpt","Please Select UserOpt Yes")) ;				
					} else if (! cov.getUserOpt().equalsIgnoreCase("Y") ) {
						errors.add(new Error("01","UserOpt","Please Select UserOpt Yes")) ;
					}
					if (StringUtils.isBlank(cov.getSubCoverYn())  ) {
						errors.add(new Error("01","SubCoverYn","Please Select SubCover Yes/No")) ;				
					} else if (! (cov.getSubCoverYn().equalsIgnoreCase("Y") || cov.getSubCoverYn().equalsIgnoreCase("N") ) ) {
						errors.add(new Error("01","SubCoverYn","Please Select SubCover Yes/No")) ;
					} else if( cov.getSubCoverYn().equalsIgnoreCase("Y") && cov.getSubCoverId() ==null ) {
						errors.add(new Error("01","SubCoverYn","Please Enter SubCover Id")) ;
					}
				}
			}
			
		} catch(Exception e){
			e.printStackTrace();
			log.info("Log Details" + e.getMessage());
			return null;
			
		}return errors;
	}


	@Override
	public UpdateCoverRes updateFactorIsSelectedDetails(UpdateFactorRateReq req) {
		UpdateCoverRes res = new UpdateCoverRes();
		try {
		//	EserviceMotorDetails  findMot = eserMotorRepo.findByRequestReferenceNoAndVehicleId(req.getRequestReferenceNo() , req.getVehicleId());
			List<FactorRateRequestDetails> findCovers = repository.findByRequestReferenceNoAndVehicleIdAndCompanyIdAndProductIdAndSectionIdOrderByCoverIdAsc(req.getRequestReferenceNo() , req.getVehicleId() ,
					req.getCompanyId() , Integer.valueOf(req.getProductId()) , Integer.valueOf(req.getSectionId())   ) ;
			
			for (CoverIdsReq covReq :    req.getCoverIdList()  ) {
				
				if(covReq.getSubCoverYn()==null || covReq.getSubCoverYn().equalsIgnoreCase("N") ) {
					List<FactorRateRequestDetails> filterCover = findCovers.stream().filter( o -> o.getCoverId().equals(covReq.getCoverId()) ).collect(Collectors.toList()); 
					
					if(filterCover.size()>0 ) {
						for (FactorRateRequestDetails  updateCover : filterCover ) {
					
							updateCover.setUserOpt(covReq.getUserOpt());
							repository.save(updateCover);
						}
	
					}
				} else {
					List<FactorRateRequestDetails> filterSubCover = findCovers.stream().filter( o -> o.getCoverId().equals(covReq.getCoverId()) && o.getSubCoverId().equals(Integer.valueOf(o.getSubCoverId()))     ).collect(Collectors.toList());
					if(filterSubCover.size()>0 ) {
						for (FactorRateRequestDetails  updateSubCover : filterSubCover ) {
							updateSubCover.setUserOpt(covReq.getUserOpt());
							repository.save(updateSubCover);
						}
						
					}
					
				}
				
			}
			
			// Get Updated Covers
			findCovers = repository.findByRequestReferenceNoAndVehicleIdOrderByCoverIdAsc(req.getRequestReferenceNo() , req.getVehicleId());
			Map<Integer,List<FactorRateRequestDetails>> groupByCover = findCovers.stream().collect(Collectors.groupingBy(FactorRateRequestDetails :: getCoverId));			
			
			List<Cover> coverListRes = 	getCoversList(groupByCover);
			coverListRes.sort(Comparator.comparing(Cover :: getCoverId).reversed() );
			res.setCoverList(coverListRes);
		//	res.setBranchCode(findCovers.get(0).getBranchCode());
			res.setInsuranceId(findCovers.get(0).getCompanyId());
			res.setProductId(findCovers.get(0).getProductId().toString());
			res.setRequestReferenceNo(req.getRequestReferenceNo());	
			res.setSectionId(findCovers.get(0).getSectionId().toString());
			res.setResponse("Cover Updated Successfully");			
			
		} catch(Exception e){
			e.printStackTrace();
			log.info("Log Details" + e.getMessage());
			return null;
			
		}return res;
	}
}
