/*
 * Created on 2023-03-03 ( 18:58:32 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.eway.oracle;

import java.io.Serializable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;



/**
 * Composite primary key for entity "MotCommDiscountDetail" ( stored in table "mot_comm_discount_detail" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class MotCommDiscountDetailIdOra implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    private String     commercialDiscount ;
    
    private String     requestreferenceno ;
    
    private Integer     riskId ;
    
    private Integer     cvrId ;
    
     
}
