/*
 * Java domain class for entity "EserviceMotorDetails" 
 * Created on 2022-10-17 ( Date ISO 2022-10-17 - Time 11:50:07 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
package com.maan.eway.common.res;

import java.io.Serializable;
import java.util.Date;

import com.fasterxml.jackson.annotation.JsonFormat;
import com.fasterxml.jackson.annotation.JsonProperty;

import lombok.AllArgsConstructor;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

 
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
public class SearchEserviceMotorDetailsRes implements Serializable {

    private static final long serialVersionUID = 1L;

    @JsonProperty("RequestReferenceNo")
   	private  String requestReferenceNo;
    @JsonProperty("QuoteNo")
   	private  String quoteNo;
    @JsonProperty("PolicyNo")
   	private  String policyNo;
    @JsonProperty("CustomerId")
   	private  String customerId;
	@JsonProperty("HavePromoCode")
    private String     havepromocode ;
    @JsonProperty("Promocode")
   	private  String promocode;
    
    
    @JsonFormat(pattern="dd/MM/yyyy")
    @JsonProperty("QuatationDate")
    private Date       entryDate ;

    @JsonFormat(pattern="dd/MM/yyyy")
    @JsonProperty("InceptionDate")
    private Date       policyStartDate ;
    
    @JsonFormat(pattern="dd/MM/yyyy")
    @JsonProperty("ExpiryDate")
    private Date       policyEndDate ;    
    
	@JsonFormat(pattern="dd/MM/yyyy")
	@JsonProperty("RegistrationYear")
    private Date   registrationYear ;
	@JsonProperty("RegistrationAge")
    private Integer registrationAge;


	@JsonProperty("EngineNumber")
    private String     engineNumber ;

	@JsonProperty("Registrationnumber")
    private String     registrationNumber ;
	@JsonProperty("Chassisnumber")
    private String     chassisNumber ;

	@JsonProperty("VehiclemakeDesc")
    private String     vehicleMakeDesc  ;
	@JsonProperty("VehcilemodelDesc")
    private String     vehcileModelDesc ;
	@JsonProperty("VehicleTypeDesc")
    private String     vehicleTypeDesc  ;
	@JsonProperty("ModelNumber")
    private String     modelNumber  ;

	@JsonProperty("ClaimRatio")
    private String claimRatio;
	@JsonProperty("NoOfClaims")
    private Integer    noOfClaims ;
	@JsonProperty("NcdYears")   
    private Integer ncdYears;
	@JsonProperty("NcdYn")
    private String    ncdYn ;
	
	@JsonProperty("ManufactureYear")
    private String manufactureYear;
	@JsonProperty("InsuranceTypeDesc")
    private String     insuranceTypeDesc;
	@JsonProperty("SumInsured")
    private Double     sumInsured   ;
	@JsonProperty("SeatingCapacity")
    private Integer    seatingCapacity ;	
	@JsonProperty("Gpstrackinginstalled")
    private String     gpsTrackingInstalled ;
	@JsonProperty("Motorusage")
    private String     motorUsage   ;
	
	@JsonProperty("MotorCategoryDesc")
    private String     motorCategoryDesc ;


	@JsonProperty("FuelTypeDesc")
    private String     fuelTypeDesc     ;
	@JsonProperty("PolicyTypeDesc")
    private String     policyTypeDesc   ;	

	@JsonProperty("Currency")
    private String     currency   ;	
	
	@JsonProperty("AcccessoriesSumInsured")
    private String     acccessoriesSumInsured ;
	@JsonProperty("WindScreenSumInsured")
	private String     windScreenSumInsured ;
	@JsonProperty("ExtendedTPPDSumInsured")
	private String     tppdIncreaeLimit ;
	
	@JsonProperty("CollateralYn")
	private String     collateralYn ;
	
	@JsonProperty("CollateralName")
	private String     collateralName ;
	
	@JsonProperty("FirstLossPayee")
	private String     firstLossPayee ;


	@JsonProperty("BorrowerType")
	private String     borrowerType;
	

	@JsonProperty("BorrowerTypeDesc")
	private String     borrowerTypeDesc;

}
