/*
 * Java domain class for entity "BankMaster" 
 * Created on 2021-10-12 ( Date ISO 2021-10-12 - Time 16:17:06 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */
 
 /*
 * Created on 2021-10-12 ( 16:17:06 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.oracle.repo;

import java.util.List;

import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.JpaSpecificationExecutor;

import com.maan.eway.oracle.PgithPolRiskAddlInfoIdOra;
import com.maan.eway.oracle.PgithPolRiskAddlInfoOra;

 
 
public interface PgitPolRiskAddlInfoOraRepository  extends JpaRepository<PgithPolRiskAddlInfoOra,PgithPolRiskAddlInfoIdOra > , JpaSpecificationExecutor<PgithPolRiskAddlInfoOra> {

	List<PgithPolRiskAddlInfoOra> findByQuotationPolicyNo(String quotationPolicyNo);



}
