/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2023-02-04 ( Date ISO 2023-02-04 - Time 18:20:08 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2023-02-04 ( 18:20:08 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.bean;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import com.maan.eway.ui.request.Field;
import com.maan.eway.ui.service.impl.FieldConverter;

import jakarta.persistence.Table;

import lombok.*;
import jakarta.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import jakarta.persistence.*;




/**
* Domain class for entity "CompanyUiFieldgroup"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(CompanyUiFieldgroupId.class)
@Table(name="company_ui_fieldgroup")


public class CompanyUiFieldgroup implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="UI_ID", nullable=false)
    private BigDecimal uiId ;

    @Id
    @Column(name="UI_GROUPID", nullable=false)
    private BigDecimal uiGroupid ;

    //--- ENTITY DATA FIELDS 
    @Column(name="UI_LABEL", length=500)
    private String     uiLabel ;

    @Column(name="UI_PARENT")
    private BigDecimal uiParent ;

    @Convert(converter = FieldConverter.class)
    @Column(name="UI_JSON", length=1073741824)
    private Field     uiJson ;

    @Column(name="FIELD_ORDERBY")
    private BigDecimal fieldOrderby ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



