/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2023-02-04 ( Date ISO 2023-02-04 - Time 18:20:07 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2023-02-04 ( 18:20:07 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.bean;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import jakarta.persistence.Table;

import lombok.*;
import jakarta.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import jakarta.persistence.*;




/**
* Domain class for entity "CompanyUiBaseinfo"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@Table(name="company_ui_baseinfo")


public class CompanyUiBaseinfo implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="UI_ID", nullable=false)
    private BigDecimal uiId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="COMPANYID", length=5)
    private String     companyid ;

    @Column(name="PRODUCTID", length=5)
    private String     productid ;

    @Column(name="UI_SPLIT_TYPE", length=10)
    private String     uiSplitType ;

    @Column(name="UI_SPLIT_COUNT")
    private BigDecimal uiSplitCount ;

    @Column(name="UI_DESIGNTYPE", length=10)
    private String     uiDesigntype ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



