/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2023-02-04 ( Date ISO 2023-02-04 - Time 18:20:08 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2023-02-04 ( 18:20:08 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.bean;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import jakarta.persistence.Table;

import lombok.*;
import jakarta.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.util.Date;
import jakarta.persistence.*;




/**
* Domain class for entity "CompanyUiDatatypes"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@Table(name="company_ui_datatypes")


public class CompanyUiDatatypes implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @GeneratedValue(strategy=GenerationType.AUTO)
    @Column(name="UI_DT_ID", nullable=false)
    private Double     uiDtId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="UI_DT_DESC", length=100)
    private String     uiDtDesc ;

    @Column(name="UI_DT_STATUS", length=3)
    private String     uiDtStatus ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UI_DT_EFFT_FROM")
    private Date       uiDtEfftFrom ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UI_DT_EFFT_TO")
    private Date       uiDtEfftTo ;

    @Column(name="UI_DT_REMARKS", length=500)
    private String     uiDtRemarks ;

    @Column(name="UI_DT_JSON", nullable=false, length=1073741824)
    private String     uiDtJson ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



