/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-11-19 ( Date ISO 2022-11-19 - Time 13:30:10 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-11-19 ( 13:30:10 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.bean;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.math.BigDecimal;
import java.util.List;

import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "EserviceBuildingDetails"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(EservicePersonalAccidentDetailsId.class)
@Table(name="eservice_personal_accident_details")


public class EservicePersonalAccidentDetails implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="REQUEST_REFERENCE_NO", nullable=false, length=20)
    private String     requestReferenceNo ;

    @Id
    @Column(name="RISK_ID", nullable=false)
    private Integer    riskId ;

    @Id
    @Column(name="CUSTOMER_REFERENCE_NO", nullable=false, length=20)
    private String     customerReferenceNo ;

    //--- ENTITY DATA FIELDS 
    @Column(name="PRODUCT_ID", length=20)
    private String  productId ;

    @Column(name="PRODUCT_DESC", length=100)
    private String  productDesc ;

    @Column(name="SECTION_ID", length=20)
    private String  sectionId ;

    @Column(name="SECTION_DESC", length=100)
    private String sectionDesc ;

    @Column(name="OCCUPATION_DESC", length=100)
    private String occupationDesc ;

    
    @Column(name="COMPANY_ID", length=20)
    private String     companyId ;

    @Column(name="COMPANY_NAME", length=100)
    private String companyName ;

    
    @Column(name="BRANCH_CODE", length=20)
    private String     branchCode ;
       

    @Column(name="BRANCH_Name", length=100)
    private String     branchName;
       
    
    @Column(name="CATEGORY_ID", length=20)
    private String     categoryId ;
    
    @Column(name="SUM_INSURED")
    private BigDecimal sumInsured;
    
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Column(name="CREATED_BY", length=100)
    private String     createdBy ;

    @Column(name="STATUS", length=2)
    private String     status ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE")
    private Date       updatedDate ;

    @Column(name="UPDATED_BY", length=100)
    private String     updatedBy ;

    @Column(name="COUNT")
    private Integer count;

    
}



