/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-11-21 ( Date ISO 2022-11-21 - Time 15:19:50 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-11-21 ( 15:19:50 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.bean;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import lombok.*;
import jakarta.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.util.Date;
import jakarta.persistence.*;

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(EwaySharePercentageId.class)
@Table(name="eway_share_percentage")


public class EwaySharePercentage implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="QUOTE_NO", nullable=false, length=60)
    private String     quoteNo ;

    @Id
    @Column(name="COMPANY_ID", nullable=false, length=60)
    private String     companyId ;

    @Id
    @Column(name="PRODUCT_ID")
    private Integer     productId ;

    @Id
    //--- ENTITY DATA FIELDS 
    @Column(name="INSURANCE_COMPANY_ID")
    private Integer     insuranceCompanyId ;

    @Column(name="INSURANCE_COMPANY_NAME", length=1500)
    private String     insuranceCompanyName ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Column(name="STATUS", length=1)
    private String     status ;

    @Column(name="SHARE_PERCENTAGE")
    private Double     sharePercentage ;

    @Column(name="REMARKS", length=100)
    private String     remarks ;

    @Column(name="LEADER_YN", length=20)
    private String     leaderYn ;

 
}



