/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2024-01-31 ( Date ISO 2024-01-31 - Time 16:10:21 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2024-01-31 ( 16:10:21 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.bean;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import jakarta.persistence.Table;

import lombok.*;
import jakarta.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.util.Date;
import jakarta.persistence.*;




/**
* Domain class for entity "EwayMotorMakemodelMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(EwayMotorMakemodelMasterId.class)
@Table(name="eway_motor_makemodel_master")


public class EwayMotorMakemodelMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="MAKE_ID", nullable=false)
    private Integer    makeId ;

    @Id
    @Column(name="MODEL_ID", nullable=false)
    private Integer    modelId ;

    @Id
    @Column(name="BODY_ID", nullable=false)
    private Integer    bodyId ;

    @Id
    @Column(name="COMPANY_ID", nullable=false, length=100)
    private String     companyId ;

    @Id
    @Column(name="BRANCH_CODE", nullable=false, length=100)
    private String     branchCode ;

    @Id
    @Column(name="AMEND_ID", nullable=false)
    private Integer    amendId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="VEHICLEMODELCODE")
    private Integer    vehiclemodelcode ;

    @Column(name="STATUS", length=10)
    private String     status ;

    @Column(name="MAKE_NAME_EN", length=1000)
    private String     makeNameEn ;

    @Column(name="MODEL_NAME_EN", length=1000)
    private String     modelNameEn ;

    @Column(name="BODY_NAME_EN", length=1000)
    private String     bodyNameEn ;

    @Column(name="VEH_CLASS")
    private Integer    vehClass ;

    @Column(name="VEH_CLASS_EN", length=1000)
    private String     vehClassEn ;

    @Column(name="VEH_MANF_COUNTRY", length=20)
    private String     vehManfCountry ;

    @Column(name="VEH_MANF_COUNTRY_EN", length=1000)
    private String     vehManfCountryEn ;

    @Column(name="VEH_MANF_REGION")
    private Integer    vehManfRegion ;

    @Column(name="VEH_MANF_REGION_EN", length=1000)
    private String     vehManfRegionEn ;

    @Column(name="VEH_CC")
    private Integer    vehCc ;

    @Column(name="VEH_WEIGHT")
    private Integer    vehWeight ;

    @Column(name="VEH_FUELTYPE")
    private Integer    vehFueltype ;

    @Column(name="CORE_MAKE_ID", length=100)
    private String     coreMakeId ;

    @Column(name="CORE_MODEL_ID", length=100)
    private String     coreModelId ;

    @Column(name="CORE_BODY_ID", length=100)
    private String     coreBodyId ;

    @Column(name="CORE_REF_NO", length=100)
    private String     coreRefNo ;

    @Column(name="VEHICLE_TYPE_AR", length=100)
    private String     vehicleTypeAr ;

    @Column(name="MAKE_NAME_AR", length=1000)
    private String     makeNameAr ;

    @Column(name="MODEL_NAME_AR", length=1000)
    private String     modelNameAr ;

    @Column(name="OTHR_MAKE_ID_1", length=1000)
    private String     othrMakeId1 ;

    @Column(name="OTHR_MODEL_ID_1", length=1000)
    private String     othrModelId1 ;

    @Column(name="OTHR_BODY_ID_1", length=100)
    private String     othrBodyId1 ;

    @Column(name="OTHR_MAKE_ID_2", length=100)
    private String     othrMakeId2 ;

    @Column(name="OTHR_MODEL_ID_2", length=100)
    private String     othrModelId2 ;

    @Column(name="OTHR_BODY_ID_2", length=100)
    private String     othrBodyId2 ;

    @Column(name="REF_NO")
    private Integer    refNo ;

    @Column(name="BATCH_ID")
    private Integer    batchId ;

    @Temporal(TemporalType.DATE)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Column(name="ENTRY_MODE", length=100)
    private String     entryMode ;

    @Column(name="UPLOADED_BY", length=100)
    private String     uploadedBy ;

    @Column(name="PREMIA_CODE")
    private Integer    premiaCode ;

    @Column(name="MODEL_ID_OLD")
    private Integer    modelIdOld ;

    @Column(name="CORE_APP_CODE", length=100)
    private String     coreAppCode ;

    @Column(name="TPLRATE")
    private Integer    tplrate ;

    @Column(name="BASERATE")
    private Integer    baserate ;

    @Column(name="NETRATE")
    private Integer    netrate ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFFECTIVE_DATE_END")
    private Date       effectiveDateEnd ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="EFFECTIVE_DATE_START")
    private Date       effectiveDateStart ;

    @Column(name="REMARKS", length=100)
    private String     remarks ;

    @Column(name="OBSOLETE_FLAG", length=100)
    private String     obsoleteFlag ;

    @Column(name="ROP_BODYID")
    private Integer    ropBodyid ;

    @Column(name="REGULATORY_CODE", length=100)
    private String     regulatoryCode ;

    @Column(name="CREATED_BY", length=30)
    private String     createdBy ;

    @Column(name="UPDATED_BY", length=30)
    private String     updatedBy ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATED_DATE")
    private Date       updatedDate ;

    @Column(name="SECTION_ID", length=10)
    private String     sectionId ;


    //--- ENTITY LINKS ( RELATIONSHIP )


}



