/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2024-02-03 ( Date ISO 2024-02-03 - Time 11:39:26 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2024-02-03 ( 11:39:26 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.bean;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import jakarta.persistence.Table;

import lombok.*;
import jakarta.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.util.Date;
import jakarta.persistence.*;




/**
* Domain class for entity "EwayFactorResultDetail"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(EwayFactorResultDetailId.class)
@Table(name="eway_factor_result_detail")


public class EwayFactorResultDetail implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="REQUEST_REFERENCE_NO", nullable=false, length=20)
    private String     requestReferenceNo ;

    @Id
    @Column(name="VEHICLE_ID", nullable=false)
    private Integer    vehicleId ;

    @Id
    @Column(name="COVER_ID", nullable=false)
    private Integer    coverId ;

    @Id
    @Column(name="COMPANY_ID", nullable=false, length=10)
    private String     companyId ;

    @Id
    @Column(name="PRODUCT_ID", nullable=false)
    private Integer    productId ;

    @Id
    @Column(name="SECTION_ID", nullable=false)
    private Integer    sectionId ;

    //--- ENTITY DATA FIELDS 
    @Column(name="CD_REFNO", length=20)
    private String     cdRefno ;

    @Column(name="VD_REFNO", length=20)
    private String     vdRefno ;

    @Column(name="MS_REFNO", length=20)
    private String     msRefno ;

    @Column(name="COVER_NAME", length=100)
    private String     coverName ;

    @Column(name="RISK_PREMIUM_AMT")
    private Double     riskPremiumAmt ;

    @Column(name="RISK_PREMIUM_RATE")
    private Double     riskPremiumRate ;

    @Column(name="TARGET_LOSS_RATIO")
    private Double     targetLossRatio ;

    @Column(name="MIN_RATE")
    private Double     minRate ;

    @Column(name="MIN_PREMIUM")
    private Double     minPremium ;

    @Column(name="FINAL_PREMIUM_AMT_EXCL_TAX")
    private Double     finalPremiumAmtExclTax ;

    @Column(name="FINAL_PREMIUM_RATE_EXCL_TAX")
    private Double     finalPremiumRateExclTax ;

    @Column(name="PRO_RATA_PREMIUM_AMT_EXCL_TAX")
    private Double     proRataPremiumAmtExclTax ;

    @Column(name="STATUS", length=2)
    private String     status ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Column(name="CREATED_BY", length=100)
    private String     createdBy ;

    
    @Column(name="MIN_RATE_LOAD")
    private Double     minRateLoad ;

    @Column(name="MIN_PREMIUM_LOAD")
    private Double     minPremiumLoad ;

    //--- ENTITY LINKS ( RELATIONSHIP )


}



