/*
 * Created on 2022-11-21 ( 15:20:06 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.eway.bean;

import java.io.Serializable;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

@AllArgsConstructor
@NoArgsConstructor
@Getter
@Setter
public class ExclusionMasterId implements Serializable {

	private static final long serialVersionUId = 1L;
	private Integer exclusionId;
	private String branchCode;
	private String companyId;
	private Integer amendId;

}
