/*
 * Created on 2022-11-21 ( 15:20:21 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.eway.bean;

import lombok.*;
import jakarta.persistence.*;
import java.io.Serializable;
import java.util.List;


import java.util.Date;

/**
 * Composite primary key for entity "NotifTemplateMaster" ( stored in table "notif_template_master" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class NotifTemplateMasterId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
   /* private Integer    sno ;
    
    private String     branchCode ;
    
    private String     companyId ;
    
    private Integer    amendId ;
    
    private String     queryKey ;
    */
    
   private Long       notifTemplateCode ;
    
    private String     companyId ;
    
    private Long       productId ;
    
    private Integer    amendId ;
     
}
