/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2023-01-04 ( Date ISO 2023-01-04 - Time 13:04:14 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2023-01-04 ( 13:04:14 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.bean;


import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import javax.persistence.Table;

import lombok.*;
import javax.persistence.*;
import java.io.Serializable;
import java.util.List;

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.*;




/**
* Domain class for entity "PolicyDrcrDetail"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(PolicyDrcrDetailId.class)
@Table(name="policy_drcr_detail")


public class PolicyDrcrDetail implements Serializable {
 
private static final long serialVersionUID = 1L;
 
    //--- ENTITY PRIMARY KEY 
    @Id
    @Column(name="POLICY_NO", nullable=false, length=50)
    private String     policyNo ;

    @Id
    @Column(name="QUOTE_NO", nullable=false, length=50)
    private String     quoteNo ;

    @Id
    @Column(name="CHG_ID", nullable=false)
    private BigDecimal chgId ;

    @Id
    @Column(name="COMPANY_ID", nullable=false, length=10)
    private String     companyId ;

    @Id
    @Column(name="PRODUCT_ID", nullable=false, length=10)
    private String     productId ;

  //  @Id
    @Column(name="SECTION_ID",  length=10)
    private String     sectionId ;

    @Id
    @Column(name="BRANCH_CODE", nullable=false, length=10)
    private String     branchCode ;

    //--- ENTITY DATA FIELDS 
    @Column(name="CHARGE_CODE")
    private BigDecimal chargeCode ;

    @Column(name="DOC_NO", length=50)
    private String     docNo ;

    @Column(name="DOC_TYPE", length=5)
    private String     docType ;

    @Column(name="DOC_ID", length=50)
    private String     docId ;

    @Column(name="AMOUNT_LC")
    private BigDecimal amountLc ;
    
    @Column(name="AMOUNT_FC")
    private BigDecimal amountFc ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ENTRY_DATE")
    private Date       entryDate ;

    @Column(name="DRCR_FLAG", length=5)
    private String     drcrFlag ;
    
    @Column(name="STATUS", length=5)
    private String     status ;

    @Column(name="RISK_ID", length=2)
    private String     riskId ;
    
    //--- ENTITY LINKS ( RELATIONSHIP )


}



