/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-11-21 ( Date ISO 2022-11-21 - Time 15:19:49 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-11-21 ( 15:19:49 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.bean;


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;




/**
* Domain class for entity "AcExecutiveMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@Table(name="renew_status_master")


public class RenewStatusMaster implements Serializable {
 
private static final long serialVersionUID = 1L;
 
@Id
@Column(name = "SNO", nullable = false)
private Double sno;

@Column(name = "CURRENT_STAGE", length = 100)
private String currentStage;

@Column(name = "CURRENT_STAGE_CODE", length = 10)
private String currentStageCode;

@Column(name = "CURRENT_STATUS_DESC", length = 100)
private String currentStatusDesc;

@Column(name = "CURRENT_STATUS_CODE", length = 10)
private String currentStatusCode;

@Column(name = "STATUS_DESC", length = 100)
private String statusDesc;

@Column(name = "STATUS", length = 10)
private String status;

@Column(name = "PRODUCT", length = 100)
private String product;

@Column(name = "ENTRY_DATE")
private Date entryDate;

@Column(name = "DISPLAY_ORDER")
private Double displayOrder;

@Column(name = "DISPLAY_NAME", length = 50)
private String displayName;

@Column(name = "DISPLAY_COLOR", length = 50)
private String displayColor;

@Column(name = "Company_id")
private Integer companyId;
    
    
}



