/*
 * Created on 2022-11-21 ( 15:19:49 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */
package com.maan.eway.bean;

import lombok.*;
import jakarta.persistence.*;
import java.io.Serializable;
import java.util.List;


import java.util.Date;

/**
 * Composite primary key for entity "AcExecutiveMaster" ( stored in table "ac_executive_master" )
 *
 * @author Telosys
 *
 */

@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Builder
public class RenewDriverDetailsId implements Serializable {

    private static final long serialVersionUID = 1L;

    //--- ENTITY KEY ATTRIBUTES 
    @Column(name="RISK_ID", nullable=false)   //--- ENTITY PRIMARY KEY 
	private Integer    riskId ;
	
	@Column(name="OLD_REQUEST_REFERENCE_NO", nullable=false)
	private String     oldrequestreferenceNo ;
	 
	@Column(name="DRIVER_ID", nullable=false)
	private Integer     driverId ;
	
	@Column(name="ID_NUMBER", nullable=false)
	private String     idNumber ;
    
 
}
