/* 
*  Copyright (c) 2019. All right reserved
 * Created on 2022-11-21 ( Date ISO 2022-11-21 - Time 15:19:49 )
 * Generated by Telosys Tools Generator ( version 3.3.0 )
 */

/*
 * Created on 2022-11-21 ( 15:19:49 )
 * Generated by Telosys ( http://www.telosys.org/ ) version 3.3.0
 */


package com.maan.eway.bean;


import java.io.Serializable;
import java.math.BigDecimal;
import java.util.Date;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.Id;
import jakarta.persistence.IdClass;
import jakarta.persistence.Table;
import jakarta.persistence.Temporal;
import jakarta.persistence.TemporalType;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;




/**
* Domain class for entity "AcExecutiveMaster"
*
* @author Telosys Tools Generator
*
*/
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@ToString
@Entity
@DynamicInsert
@DynamicUpdate
@Builder
@IdClass(RenewQuotePolicyId.class)
@Table(name="renew_quote_policy")


public class RenewQuotePolicy implements Serializable {
 
private static final long serialVersionUID = 1L;
 
	@Id
	@Column(name="TRAN_ID", nullable=false)   //--- ENTITY PRIMARY KEY 
	private String    tranId ;
	
	@Id
	@Column(name="OLD_REQUEST_REF_NO", nullable=false)
	private String     oldrequestreferenceNo ;
	 
	@Id
	@Column(name="OLD_POLICY_NO", nullable=false)
	private String     oldpolicyNo ;

    @Column(name="SERVICE_TYPE", nullable=false, length=20)
    private String     serviceType ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="REQUEST_TIME", nullable=false)
    private Date     requestTime ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="RESPONSE_TIME", nullable=false)
    private Date       responseTime ;
 
    @Column(name="STATUS", length=100)
    private String     status ;

    @Column(name="OLD_QUOTE_NO", length=20)
    private String     oldquoteNo ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="OLD_START_DATE")
    private Date     oldstartDate ;

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="OLD_END_DATE", nullable=false)
    private Date       oldendDate ;

    @Column(name="TITLE")
    private String    title ;

    @Column(name="CUSTOMER_NAME")
    private String    customerName ;
    
    @Column(name="GENDER")
    private String    gender ;
    
    @Column(name="OCCUPATION")
    private String    occupation ;
    
    @Column(name="MOBILE_CODE")
    private String    mobileCode ;
    
    @Column(name="MOBILE_NO")
    private String    mobileNo ;
    
    @Column(name="EMAIL_ID")
    private String    emailId ;
    
    @Column(name="IDENTITY_TYPE")
    private String    identityType ;
    
    @Column(name="IDENTITY_NUMBER")
    private String    identityNumber ;
    
    @Column(name="PREFERRED_NOTIFICATION")
    private String    preferedNotification ;
    
    @Column(name="TAX_EXCEMPTION")
    private String    taxExcemption ;
    
    @Column(name="STREET")
    private String    street ;
    
    @Column(name="COUNTRY")
    private String    country ;
    
    @Column(name="REGION")
    private String    region ;
    
    @Column(name="DISTRICT")
    private String    district ;
    
    @Column(name="POBOX")
    private String    pobox ;
    
    @Column(name="NO_OF_VEHICLE")
    private String    noofVehicle ;
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="NEW_START_DATE")
    private Date    newstartDate ;
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="NEW_END_DATE")
    private Date    newendDate ;
    
    @Column(name="NEW_PREMIUM")
    private BigDecimal    newPremium ;
    
    @Column(name="NEW_POLICY_NUMBER")
    private String    newpolicyNumber ;
    
    @Column(name="CURRENT_STATUS")
    private String    currentStatus ;
    
    @Column(name="CURRENT_STAGE_CODE")
    private String    currentStageCode ;
    
    @Column(name="CURRENT_STATUS_CODE")
    private String    currentStatusCode ;
    
    @Column(name="LOGIN_ID")
    private String    loginId ;
    
    @Column(name="AAPLICATION_ID")
    private String    applicationId ;
    
    @Column(name="COMPANY_ID")
    private String    companyId ;
    
    @Column(name="PRODUCT_CODE")
    private String    productCode ;
    
    @Column(name="SECTION_CODE")
    private String    sectionCode ;
    
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="VIEWED_DATE")
    private Date    viewDate ;
    
    @Column(name="BRANCH_CODE")
    private String    branchCode ;
    
    @Column(name="BRANCH_NAME")
    private String    branchName ;
    
    @Column(name="REMARKS")
    private String    remarks ;
    
    @Column(name="LAST_NOTIFY_YN")
    private String    lastNotifyYN ;

    
}



