/*
*  Copyright (c) 2019. All right reserved
* Created on 2022-08-24 ( Date ISO 2022-08-24 - Time 12:58:26 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.maan.eway.master.service;

import java.util.List;

import com.maan.eway.master.req.BranchChangeStatusReq;
import com.maan.eway.master.req.BranchMasterGetAllReq;
import com.maan.eway.master.req.BranchMasterGetReq;
import com.maan.eway.master.req.BranchMasterSaveReq;
import com.maan.eway.master.req.CompanyBranchGetReq;
import com.maan.eway.master.req.CompanyBranchReq;
import com.maan.eway.master.res.BranchMasterRes;
import com.maan.eway.res.DropDownRes;
import com.maan.eway.res.SuccessRes;
/**
* <h2>BankMasterServiceimpl</h2>
*/
public interface BranchMasterService  {

	List<DropDownRes> getBranchMasterDropdown(CompanyBranchGetReq req);

	BranchMasterRes getByBranchCode(BranchMasterGetReq req);

	List<BranchMasterRes> getActiveBranchDetails(BranchMasterGetAllReq req);

	List<BranchMasterRes> getallBranchDetails(BranchMasterGetAllReq req);

	SuccessRes insertBranch(BranchMasterSaveReq req);

	List<String> validateBranchDetails(BranchMasterSaveReq req);

	List<DropDownRes> getCompanyBranchMasterDropdown(CompanyBranchReq req);

	SuccessRes changeStatusOfBranch(BranchChangeStatusReq req);





}
