/*
*  Copyright (c) 2019. All right reserved
* Created on 2022-08-24 ( Date ISO 2022-08-24 - Time 12:58:26 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.maan.eway.master.service;

import java.util.List;

import com.maan.eway.error.Error;
import com.maan.eway.master.req.EmiEndtDetailsReq;
import com.maan.eway.master.req.EmiInstallmentDetailsReq;
import com.maan.eway.master.req.EmiTransactionDetailsGetReq;
import com.maan.eway.master.req.EmiTransactionDetailsNextReq;
import com.maan.eway.master.req.EmiTransactionDetailsSaveReq;
import com.maan.eway.master.req.EmiTransactionDetailsUpdateReq;
import com.maan.eway.master.res.EmiTransactionDetailsRes;
import com.maan.eway.master.res.EmiDisplayRes;
import com.maan.eway.res.SuccessRes;

public interface EmiTransactionDetailsService  {

	List<Error> validateEmiTransactionDetails(EmiTransactionDetailsSaveReq req);

	SuccessRes insertEmiTransactionDetails(EmiTransactionDetailsSaveReq req);

	List<EmiDisplayRes> viewEmiInstallmentDetails(EmiInstallmentDetailsReq req);

	List<Error> validateEmiInstallmentDetails(EmiInstallmentDetailsReq req);

	SuccessRes updateEmiTransactionDetails(List<EmiTransactionDetailsUpdateReq> req);

	List<Error> validateUpdateEmiTransactionDetails(List<EmiTransactionDetailsUpdateReq> req);

	List<EmiTransactionDetailsRes> getEmiDetailsByQuoteNo(EmiTransactionDetailsGetReq req);

	List<EmiTransactionDetailsRes> getNextEmiDetails(EmiTransactionDetailsNextReq req);

	SuccessRes getEndorsementEmiDetails(EmiTransactionDetailsSaveReq req);

}
