/*
*  Copyright (c) 2019. All right reserved
* Created on 2022-08-24 ( Date ISO 2022-08-24 - Time 12:58:26 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.maan.eway.master.service;

import java.util.List;

import com.maan.eway.master.req.IndustryMasterChangeStatusReq;
import com.maan.eway.master.req.IndustryMasterDropdownReq;
import com.maan.eway.master.req.IndustryMasterGetReq;
import com.maan.eway.master.req.IndustryMasterGetallReq;
import com.maan.eway.master.req.IndustryMasterSaveReq;
import com.maan.eway.master.res.IndustryMasterRes;
import com.maan.eway.res.IndustryDropDownRes;
import com.maan.eway.res.SuccessRes;

public interface IndustryMasterService  {

	List<IndustryDropDownRes> getIndustryMasterDropdown(IndustryMasterDropdownReq req);

	List<String> validateIndustryDetails(IndustryMasterSaveReq req);

	SuccessRes insertIndustry(IndustryMasterSaveReq req);

	List<IndustryMasterRes> getallIndustry(IndustryMasterGetallReq req);

	List<IndustryMasterRes> getActiveIndustryMaster(IndustryMasterGetallReq req);

	IndustryMasterRes getByIndustryId(IndustryMasterGetReq req);

	SuccessRes changeStatus(IndustryMasterChangeStatusReq req);


	

}
