/*
*  Copyright (c) 2019. All right reserved
* Created on 2022-10-11 ( Date ISO 2022-10-11 - Time 15:28:59 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.maan.eway.master.service;

import java.util.List;

import com.maan.eway.master.req.UsageDropDownReq;
import com.maan.eway.res.DropDownRes;

/**
* <h2>PersonalInfoServiceimpl</h2>
*/
public interface MotorVeicleUsageMasterService  {

	/*List<Error> validateMotorVehicleUsageDetails(MotorVehicleUsageMasterSaveReq req);

	SuccessRes saveMotorVehicleUsageDetails(MotorVehicleUsageMasterSaveReq req);

	MotorVehicleUsageMasterGetRes getMotorVehicleDetails(MotorVehicleUsageMasterGetReq req);

	List<MotorVehicleUsageMasterGetRes> getallMotorVehicleDetails(MotorVehicleUsageMasterGetallReq req);

	List<MotorVehicleUsageMasterGetRes> getactiveMotorVehicleDetails(MotorVehicleUsageMasterGetallReq req);

	
	SuccessRes changeStatusOfVehicleUsage(MotorVehicleUsageChangeStatusReq req);*/

	List<DropDownRes> getVehicleUsageDropdown(UsageDropDownReq req);

	
}
