/*
*  Copyright (c) 2019. All right reserved
* Created on 2022-08-24 ( Date ISO 2022-08-24 - Time 12:58:26 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.maan.eway.master.service;

import java.util.List;

import com.maan.eway.master.controller.OccupationDropDownReq;
import com.maan.eway.res.DropDownRes;
/**
* <h2>BankMasterServiceimpl</h2>
*/
public interface OccupationMasterService  {

	/*
	List<Error> validateOccupation(OccupationMasterSaveReq req);

	SuccessRes insertOccupation(OccupationMasterSaveReq req);

	List<OccupationMasterRes> getallOccupation(OccupationMasterGetAllReq req);

	OccupationMasterRes getByOccupationId(OccupationMasterGetReq req);

	List<OccupationMasterRes> getActiveOccupation(OccupationMasterGetAllReq req);
	SuccessRes changeStatusOfOccupation(OccupationChangeStatusReq req);
*/

	List<DropDownRes> getOccupationMasterDropdown(OccupationDropDownReq req);
}
