/*
*  Copyright (c) 2019. All right reserved
* Created on 2022-08-24 ( Date ISO 2022-08-24 - Time 12:58:26 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.maan.eway.master.service;

import java.util.List;

import com.maan.eway.master.req.RegionChangeStatusReq;
import com.maan.eway.master.req.RegionMasterDropDownReq;
import com.maan.eway.master.req.RegionMasterGetAllReq;
import com.maan.eway.master.req.RegionMasterGetReq;
import com.maan.eway.master.req.RegionMasterSaveReq;
import com.maan.eway.master.res.RegionMasterRes;
import com.maan.eway.res.DropDownRes;
import com.maan.eway.res.SuccessRes;
/**
* <h2>BankMasterServiceimpl</h2>
*/
public interface RegionMasterService  {

	List<String> validateRegionDetails(RegionMasterSaveReq req);

	SuccessRes insertRegion(RegionMasterSaveReq req);

	List<RegionMasterRes> getallRegionDetails(RegionMasterGetAllReq req);

	List<RegionMasterRes> getActiveRegionDetails(RegionMasterGetAllReq req);

	RegionMasterRes getByRegionCode(RegionMasterGetReq req);

	//List<DropDownRes> getRegionMasterDropdown(RegionMasterDropDownReq req);

	List<DropDownRes> getRegionMasterDropdown(RegionMasterDropDownReq req);
	SuccessRes changeStatusOfRegion(RegionChangeStatusReq req);



}
