/*
*  Copyright (c) 2019. All right reserved
* Created on 2022-11-08 ( Date ISO 2022-11-08 - Time 16:28:23 )
* Generated by Telosys Tools Generator ( version 3.3.0 )
*/
package com.maan.eway.service;
import java.util.List;

import com.maan.eway.bean.FactorRateRequestDetails;
import com.maan.eway.common.req.EserviceMotorDetailsSaveRes;
import com.maan.eway.req.FactorRateDetailsGetReq;
import com.maan.eway.res.SuccessRes;
/**
* <h2>FactorRateRequestDetailsServiceimpl</h2>
*/
public interface FactorRateRequestDetailsService  {

FactorRateRequestDetails create(FactorRateRequestDetails d);
FactorRateRequestDetails update(FactorRateRequestDetails d);
//FactorRateRequestDetails getOne(long id) ;
 List<FactorRateRequestDetails> getAll();
long getTotal();
//boolean delete(long id);
EserviceMotorDetailsSaveRes getFactorRateRequestDetails(FactorRateDetailsGetReq req);
SuccessRes saveFactorRateRequestDetails(EserviceMotorDetailsSaveRes req);

}
